timeunit 10ns; timeprecision 100ps;

// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

module control(ALE, AluEn, AluWe, AluOR, CFlag, ENB, ImmSel, IrWe,
     LrEn, LrSel, LrWe, MemEn, nME, nOE, nWE, Op1Sel, Op2Sel, PcEn,
     PcSel, PcWe, RegWe, Rs1Sel, RwSel, WdSel, SysBus, Clock, Flags,
     nIRQ, nReset, nWait, OpcodeCondIn);
  input Clock, nIRQ, nReset, nWait;
  input [3:0] Flags;
  input [7:0] OpcodeCondIn;
  output ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel,
       LrWe, MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel;
  output [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  output [2:0] PcSel;
  inout [15:0] SysBus;
  wire Clock, nIRQ, nReset, nWait;
  wire [3:0] Flags;
  wire [7:0] OpcodeCondIn;
  wire ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel, LrWe,
       MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel;
  wire [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  wire [2:0] PcSel;
  wire [15:0] SysBus;
  wire IRQ1, IRQ2, InISR, IntReq, \StatusReg[0] , \StatusReg[2] ,
       \StatusReg[3] , n_0;
  wire n_2, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_254, n_255, n_256;
  wire n_257, n_258, n_259, n_260, n_261, n_262, n_263, n_264;
  wire n_265, n_266, n_267, n_268, n_269, n_270, n_272, n_273;
  wire n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_286, n_287, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_294, n_295, n_296, n_297, n_298;
  wire n_300, n_301, n_302, n_303, n_305, n_306, n_307, n_309;
  wire n_310, n_311, n_312, n_313, n_314, n_315, n_316, n_317;
  wire n_318, n_319, n_320, n_321, n_323, n_325, n_326, n_327;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_340, n_341, n_342, n_343, n_344, n_345;
  wire n_346, n_347, n_348, n_349, n_350, n_351, n_352, n_353;
  wire n_355, n_356, n_358, n_359, n_360, n_361, n_362, n_365;
  wire n_366, n_367, n_368, n_369, n_370, n_374, n_375, n_376;
  wire n_377, n_378, n_379, n_380, n_381, n_382, n_383, n_386;
  wire n_387, n_390, n_391, n_392, n_394, n_396, n_397, n_398;
  wire n_399, n_400, n_401, n_403, n_404, n_405, n_512, n_513;
  wire n_514, n_515, n_516, \stateSub[0] , \stateSub[1] , \stateSub[2]
       , \state[0] , \state[1] ;
  nand4 g9579(.A (n_320), .B (n_175), .C (n_404), .D (n_321), .Y
       (Rs1Sel[0]));
  nand4 g9593(.A (n_250), .B (n_245), .C (n_396), .D (n_405), .Y
       (Op2Sel[1]));
  nand3 g9582(.A (n_405), .B (n_392), .C (n_398), .Y (RegWe));
  scandtype \StatusReg_reg[3] (.nReset (nReset), .Clock (Clock), .D
       (n_397), .Q (\StatusReg[3] ), .nQ (n_515));
  scandtype InISR_reg(.nReset (nReset), .Clock (Clock), .D (n_399), .Q
       (InISR), .nQ (n_516));
  inv g9580(.A (n_403), .Y (n_404));
  scandtype \StatusReg_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_391), .Q (\StatusReg[0] ), .nQ (n_513));
  scandtype \StatusReg_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_401), .Q (CFlag), .nQ ());
  scandtype \StatusReg_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_400), .Q (\StatusReg[2] ), .nQ (n_514));
  nand4 g9581(.A (n_43), .B (n_117), .C (n_386), .D (n_140), .Y
       (n_403));
  nand4 g9592(.A (n_223), .B (n_327), .C (n_381), .D (n_394), .Y (nOE));
  nand3 g9596(.A (n_349), .B (n_379), .C (n_341), .Y (n_401));
  nand3 g9597(.A (n_347), .B (n_378), .C (n_338), .Y (n_400));
  nand2 g9614(.A (n_382), .B (n_398), .Y (n_399));
  nand3 g9598(.A (n_346), .B (n_376), .C (n_337), .Y (n_397));
  inv g9619(.A (n_390), .Y (n_396));
  nand3 g9594(.A (n_394), .B (n_374), .C (n_123), .Y (PcEn));
  nand2 g9603(.A (n_387), .B (n_405), .Y (Rs1Sel[1]));
  nor2 g9590(.A (n_380), .B (n_246), .Y (n_392));
  nand3 g9595(.A (n_350), .B (n_367), .C (n_342), .Y (n_391));
  nand4 g9620(.A (n_359), .B (n_258), .C (n_256), .D (n_125), .Y
       (n_390));
  scandtype \stateSub_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_370), .Q (\stateSub[0] ), .nQ (n_276));
  nand4 g9618(.A (n_365), .B (n_281), .C (n_277), .D (n_398), .Y
       (AluWe));
  nand3 g9604(.A (n_368), .B (n_334), .C (n_235), .Y (ImmSel));
  nor2 g9612(.A (n_362), .B (n_286), .Y (n_387));
  inv g9587(.A (n_375), .Y (n_386));
  nand3 g9657(.A (n_77), .B (n_383), .C (n_289), .Y (MemEn));
  nand3 g9632(.A (n_316), .B (n_383), .C (n_352), .Y (nWE));
  nand2 g9629(.A (InISR), .B (n_366), .Y (n_382));
  inv g9633(.A (n_369), .Y (n_381));
  nand4 g9606(.A (n_233), .B (n_202), .C (n_351), .D (n_252), .Y
       (n_380));
  nand2 g9609(.A (SysBus[1]), .B (n_377), .Y (n_379));
  nand2 g9610(.A (SysBus[2]), .B (n_377), .Y (n_378));
  nand2 g9611(.A (SysBus[3]), .B (n_377), .Y (n_376));
  nand4 g9588(.A (n_30), .B (n_38), .C (n_335), .D (n_17), .Y (n_375));
  nand2 g9615(.A (n_353), .B (n_210), .Y (n_374));
  nand4 g9626(.A (n_273), .B (n_240), .C (n_336), .D (n_361), .Y
       (AluEn));
  nand2 g9649(.A (n_356), .B (n_76), .Y (ENB));
  nand3 g9638(.A (n_358), .B (n_323), .C (n_394), .Y (PcSel[1]));
  nand4 g9602(.A (n_105), .B (n_116), .C (n_332), .D (n_104), .Y
       (n_370));
  nand3 g9634(.A (n_171), .B (n_343), .C (n_127), .Y (n_369));
  inv g9639(.A (n_360), .Y (n_368));
  nand2 g9608(.A (SysBus[0]), .B (n_377), .Y (n_367));
  nand3 g9658(.A (\stateSub[2] ), .B (n_61), .C (n_313), .Y (n_366));
  nand2 g9672(.A (n_325), .B (n_331), .Y (n_365));
  scandtype \state_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_345), .Q (\state[0] ), .nQ (n_40));
  nand4 g9591(.A (n_319), .B (n_126), .C (n_317), .D (n_203), .Y (nME));
  nand3 g9617(.A (n_200), .B (n_310), .C (n_237), .Y (Op2Sel[0]));
  nand4 g9636(.A (n_285), .B (n_191), .C (n_249), .D (n_361), .Y
       (n_362));
  nand4 g9640(.A (n_153), .B (n_269), .C (n_247), .D (n_326), .Y
       (n_360));
  nand2 g9647(.A (n_329), .B (n_344), .Y (n_359));
  nand2 g9665(.A (n_311), .B (n_296), .Y (n_358));
  scandtype \state_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_315), .Q (\state[1] ), .nQ (n_14));
  nand2 g9675(.A (n_163), .B (n_355), .Y (n_383));
  nand3 g9630(.A (n_164), .B (n_394), .C (n_307), .Y (PcWe));
  nand2 g9676(.A (n_165), .B (n_355), .Y (n_356));
  nand4 g9635(.A (n_405), .B (n_292), .C (n_242), .D (n_398), .Y
       (RwSel[1]));
  nand2 g9625(.A (n_352), .B (n_330), .Y (n_353));
  inv g9641(.A (n_333), .Y (n_351));
  nand2 g9651(.A (n_348), .B (Flags[0]), .Y (n_350));
  nand2 g9652(.A (n_348), .B (Flags[1]), .Y (n_349));
  nand2 g9653(.A (n_348), .B (Flags[2]), .Y (n_347));
  nand2 g9654(.A (n_348), .B (Flags[3]), .Y (n_346));
  nand3 g9613(.A (n_300), .B (n_272), .C (n_67), .Y (n_345));
  nand2 g9664(.A (n_312), .B (n_197), .Y (n_344));
  nand2 g9667(.A (n_309), .B (n_266), .Y (n_343));
  nand2 g9621(.A (n_340), .B (\StatusReg[0] ), .Y (n_342));
  nand2 g9622(.A (n_340), .B (CFlag), .Y (n_341));
  nand3 g9674(.A (n_405), .B (n_298), .C (n_297), .Y (AluOR[1]));
  nand2 g9623(.A (n_340), .B (\StatusReg[2] ), .Y (n_338));
  nand2 g9624(.A (n_340), .B (\StatusReg[3] ), .Y (n_337));
  inv g9686(.A (n_314), .Y (n_336));
  nor2 g9601(.A (n_306), .B (n_115), .Y (n_335));
  nand3 g9637(.A (OpcodeCondIn[6]), .B (n_279), .C (OpcodeCondIn[4]),
       .Y (n_334));
  nand4 g9642(.A (n_187), .B (n_206), .C (n_287), .D (n_145), .Y
       (n_333));
  nand2 g9643(.A (n_305), .B (n_276), .Y (n_332));
  nand2 g9708(.A (n_303), .B (n_162), .Y (n_331));
  nand2 g9655(.A (n_288), .B (n_280), .Y (n_330));
  nand2 g9726(.A (n_329), .B (n_302), .Y (n_361));
  nand2 g9670(.A (n_327), .B (n_128), .Y (ALE));
  nand2 g9673(.A (n_325), .B (n_290), .Y (n_326));
  nand2 g9650(.A (n_323), .B (n_265), .Y (LrEn));
  nand4 g9605(.A (n_321), .B (n_320), .C (n_248), .D (n_319), .Y
       (RwSel[0]));
  trisbuf g1(.A (\StatusReg[3] ), .Enable (n_318), .Y (SysBus[3]));
  trisbuf g469(.A (\StatusReg[2] ), .Enable (n_318), .Y (SysBus[2]));
  trisbuf g470(.A (CFlag), .Enable (n_318), .Y (SysBus[1]));
  trisbuf g471(.A (\StatusReg[0] ), .Enable (n_318), .Y (SysBus[0]));
  inv g9627(.A (n_301), .Y (n_317));
  nand2 g9679(.A (n_275), .B (n_260), .Y (n_316));
  nand2 g9631(.A (n_291), .B (n_98), .Y (n_315));
  nand3 g9687(.A (n_224), .B (n_168), .C (n_261), .Y (n_314));
  inv g9690(.A (n_312), .Y (n_313));
  inv g9699(.A (n_295), .Y (n_355));
  inv g9711(.A (n_405), .Y (n_311));
  nand2 g9648(.A (n_278), .B (n_239), .Y (n_310));
  nand2 g9722(.A (n_177), .B (n_259), .Y (n_309));
  nand2 g9656(.A (n_255), .B (n_394), .Y (PcSel[0]));
  nand2 g9663(.A (n_293), .B (n_251), .Y (n_307));
  nand4 g9616(.A (n_44), .B (n_6), .C (n_211), .D (n_48), .Y (n_306));
  nand3 g9671(.A (n_263), .B (n_188), .C (n_56), .Y (n_305));
  scandtype \stateSub_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_268), .Q (\stateSub[2] ), .nQ (n_203));
  nand2 g9677(.A (n_270), .B (n_213), .Y (LrWe));
  inv g9772(.A (n_302), .Y (n_303));
  nand4 g9628(.A (n_47), .B (n_201), .C (n_300), .D (n_32), .Y (n_301));
  nand2 g9680(.A (n_231), .B (n_243), .Y (n_348));
  nand2 g9705(.A (n_298), .B (n_297), .Y (AluOR[0]));
  nand2 g9691(.A (n_294), .B (n_296), .Y (n_312));
  nor2 g9700(.A (n_294), .B (n_216), .Y (n_295));
  nand4 g9646(.A (n_100), .B (n_293), .C (n_220), .D (n_207), .Y
       (n_340));
  nand2 g9712(.A (n_215), .B (n_294), .Y (n_405));
  nand2 g9721(.A (n_225), .B (n_218), .Y (n_292));
  and2 g9723(.A (n_228), .B (n_96), .Y (n_327));
  nand3 g9659(.A (n_204), .B (IntReq), .C (\state[0] ), .Y (n_291));
  nand2 g9730(.A (n_219), .B (n_282), .Y (n_290));
  inv g9732(.A (n_267), .Y (n_318));
  nand3 g9735(.A (n_284), .B (n_288), .C (n_283), .Y (n_289));
  nand3 g9666(.A (n_241), .B (n_286), .C (nWait), .Y (n_287));
  nand3 g9750(.A (n_284), .B (n_257), .C (n_283), .Y (n_285));
  nand3 g9668(.A (n_71), .B (n_254), .C (n_13), .Y (n_323));
  scandtype IntReq_reg(.nReset (nReset), .Clock (Clock), .D (n_238), .Q
       (IntReq), .nQ ());
  nand2 g9773(.A (n_205), .B (n_282), .Y (n_302));
  nand4 g9678(.A (n_236), .B (\stateSub[1] ), .C (n_262), .D (n_296),
       .Y (n_281));
  nand4 g9681(.A (n_73), .B (n_194), .C (n_181), .D (n_180), .Y
       (n_280));
  nand2 g9682(.A (n_199), .B (n_190), .Y (n_279));
  nand3 g9685(.A (n_183), .B (n_192), .C (n_149), .Y (n_278));
  nand2 g9692(.A (n_229), .B (n_276), .Y (n_277));
  nand2 g9703(.A (n_221), .B (n_50), .Y (n_275));
  inv g9706(.A (n_273), .Y (Op1Sel));
  nand2 g9645(.A (n_208), .B (n_119), .Y (n_272));
  inv g9717(.A (n_270), .Y (LrSel));
  nand2 g9728(.A (n_286), .B (\stateSub[0] ), .Y (n_269));
  nand2 g9729(.A (n_179), .B (n_166), .Y (n_268));
  nand3 g9733(.A (n_283), .B (n_264), .C (n_266), .Y (n_267));
  nand3 g9734(.A (n_244), .B (n_264), .C (n_212), .Y (n_265));
  nand2 g9740(.A (n_262), .B (n_114), .Y (n_263));
  nand2 g9744(.A (n_262), .B (n_260), .Y (n_261));
  nand2 g9745(.A (n_262), .B (\stateSub[0] ), .Y (n_259));
  nand3 g9746(.A (n_284), .B (n_257), .C (n_226), .Y (n_258));
  and2 g9751(.A (n_283), .B (n_217), .Y (n_294));
  nand2 g9752(.A (n_227), .B (n_283), .Y (n_256));
  nand2 g9669(.A (n_198), .B (n_254), .Y (n_255));
  scandtype \stateSub_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_176), .Q (\stateSub[1] ), .nQ (n_152));
  nand2 g9768(.A (n_232), .B (n_283), .Y (n_298));
  inv g9780(.A (n_252), .Y (WdSel));
  nand2 g9689(.A (n_147), .B (n_196), .Y (n_251));
  nand2 g9693(.A (n_286), .B (n_276), .Y (n_250));
  nand2 g9698(.A (n_185), .B (n_152), .Y (n_249));
  nand2 g9707(.A (n_254), .B (n_110), .Y (n_273));
  nor2 g9644(.A (n_178), .B (n_174), .Y (n_248));
  nand2 g9709(.A (n_246), .B (n_209), .Y (n_247));
  nand3 g9710(.A (n_244), .B (n_222), .C (n_214), .Y (n_245));
  nand2 g9714(.A (n_325), .B (n_182), .Y (n_243));
  nand2 g9715(.A (n_286), .B (n_241), .Y (n_242));
  nand2 g9716(.A (n_246), .B (n_239), .Y (n_240));
  nand2 g9718(.A (n_254), .B (n_266), .Y (n_270));
  nand3 g9724(.A (n_160), .B (n_83), .C (n_99), .Y (n_238));
  nand3 g9725(.A (n_234), .B (n_186), .C (n_236), .Y (n_237));
  nand3 g9727(.A (n_234), .B (n_230), .C (n_236), .Y (n_235));
  nand3 g9736(.A (n_148), .B (n_232), .C (OpcodeCondIn[6]), .Y (n_233));
  nand3 g9737(.A (n_84), .B (n_230), .C (OpcodeCondIn[6]), .Y (n_231));
  nand2 g9742(.A (n_155), .B (n_161), .Y (n_229));
  nand2 g9747(.A (n_227), .B (n_226), .Y (n_228));
  inv g9748(.A (n_195), .Y (n_225));
  inv g9761(.A (n_189), .Y (n_224));
  nand2 g9770(.A (n_222), .B (n_244), .Y (n_223));
  nand2 g9771(.A (n_288), .B (n_226), .Y (n_221));
  and2 g9775(.A (n_135), .B (n_167), .Y (n_220));
  nand3 g9779(.A (n_296), .B (n_218), .C (n_217), .Y (n_219));
  nand3 g9781(.A (n_216), .B (n_215), .C (n_214), .Y (n_252));
  nand3 g9782(.A (n_216), .B (n_215), .C (n_212), .Y (n_213));
  nand3 g9683(.A (n_210), .B (n_158), .C (n_209), .Y (n_211));
  nand3 g9688(.A (n_172), .B (n_210), .C (n_207), .Y (n_208));
  nand3 g9695(.A (n_236), .B (n_230), .C (n_170), .Y (n_206));
  nand3 g9824(.A (n_138), .B (n_218), .C (n_33), .Y (n_205));
  nand2 g9697(.A (n_169), .B (n_203), .Y (n_204));
  nand3 g9701(.A (OpcodeCondIn[7]), .B (n_230), .C (OpcodeCondIn[3]),
       .Y (n_202));
  nand2 g9702(.A (n_173), .B (n_136), .Y (n_201));
  nand3 g9704(.A (n_20), .B (n_230), .C (OpcodeCondIn[3]), .Y (n_200));
  nand3 g9713(.A (n_78), .B (n_230), .C (n_296), .Y (n_199));
  nand4 g9731(.A (n_75), .B (n_8), .C (n_139), .D (n_79), .Y (n_198));
  and2 g9738(.A (n_230), .B (n_63), .Y (n_246));
  nor2 g9739(.A (n_184), .B (OpcodeCondIn[6]), .Y (n_286));
  nand3 g9741(.A (n_212), .B (n_159), .C (OpcodeCondIn[7]), .Y (n_197));
  nand2 g9743(.A (n_193), .B (OpcodeCondIn[7]), .Y (n_196));
  nor2 g9749(.A (n_232), .B (n_151), .Y (n_195));
  nand2 g9753(.A (n_193), .B (n_209), .Y (n_194));
  nand2 g9756(.A (n_230), .B (OpcodeCondIn[4]), .Y (n_192));
  nand2 g9757(.A (n_227), .B (n_218), .Y (n_191));
  nand2 g9758(.A (n_230), .B (OpcodeCondIn[3]), .Y (n_190));
  and2 g9760(.A (n_230), .B (n_108), .Y (n_254));
  nor2 g9762(.A (n_188), .B (n_241), .Y (n_189));
  nand2 g9763(.A (n_186), .B (n_85), .Y (n_187));
  nand2 g9764(.A (n_184), .B (n_89), .Y (n_185));
  nand2 g9776(.A (n_186), .B (OpcodeCondIn[3]), .Y (n_183));
  nand2 g9777(.A (n_181), .B (n_180), .Y (n_182));
  nand2 g9778(.A (n_150), .B (\state[1] ), .Y (n_179));
  nand4 g9684(.A (n_137), .B (n_39), .C (n_120), .D (n_102), .Y
       (n_178));
  and2 g9800(.A (n_257), .B (n_218), .Y (n_262));
  and2 g9801(.A (n_218), .B (OpcodeCondIn[7]), .Y (n_283));
  nor2 g9694(.A (n_157), .B (n_236), .Y (n_377));
  nand2 g9817(.A (n_215), .B (n_218), .Y (n_177));
  nand3 g9696(.A (n_81), .B (n_141), .C (n_62), .Y (n_176));
  inv g9719(.A (n_174), .Y (n_175));
  nand2 g9720(.A (n_142), .B (n_103), .Y (n_174));
  nand2 g9767(.A (n_133), .B (OpcodeCondIn[3]), .Y (n_173));
  nand2 g9754(.A (n_131), .B (n_156), .Y (n_172));
  nand3 g9759(.A (n_284), .B (n_154), .C (n_170), .Y (n_171));
  nand2 g9766(.A (n_210), .B (n_146), .Y (n_169));
  nand3 g9783(.A (n_244), .B (n_107), .C (n_214), .Y (n_168));
  nand2 g9789(.A (n_129), .B (OpcodeCondIn[5]), .Y (n_167));
  nand2 g9793(.A (n_165), .B (nWait), .Y (n_166));
  nand2 g9807(.A (n_164), .B (n_124), .Y (n_264));
  nand2 g9810(.A (n_164), .B (n_57), .Y (n_163));
  nand2 g9814(.A (n_143), .B (n_162), .Y (n_226));
  nand2 g9816(.A (n_257), .B (n_244), .Y (n_161));
  nand2 g9819(.A (IntReq), .B (n_394), .Y (n_160));
  nand2 g9820(.A (n_164), .B (n_122), .Y (n_222));
  nand2 g9823(.A (n_159), .B (n_212), .Y (n_282));
  nand2 g9769(.A (n_49), .B (n_118), .Y (n_158));
  nand4 g9755(.A (n_156), .B (\stateSub[2] ), .C (n_293), .D (n_94), .Y
       (n_157));
  nor2 g9785(.A (n_113), .B (n_66), .Y (n_181));
  and2 g9786(.A (n_325), .B (n_134), .Y (n_186));
  nand2 g9787(.A (n_154), .B (n_170), .Y (n_155));
  nand2 g9788(.A (n_154), .B (n_152), .Y (n_153));
  and2 g9790(.A (n_325), .B (n_236), .Y (n_151));
  nand2 g9797(.A (n_154), .B (OpcodeCondIn[3]), .Y (n_184));
  nand2 g9798(.A (n_121), .B (n_41), .Y (n_150));
  and2 g9802(.A (n_325), .B (OpcodeCondIn[5]), .Y (n_230));
  nand2 g9803(.A (n_325), .B (n_65), .Y (n_149));
  and2 g9804(.A (n_111), .B (n_148), .Y (n_193));
  inv g9805(.A (n_146), .Y (n_147));
  nand2 g9808(.A (n_325), .B (n_239), .Y (n_145));
  nor2 g9809(.A (n_154), .B (n_130), .Y (n_188));
  and2 g9811(.A (n_329), .B (\stateSub[0] ), .Y (n_227));
  and2 g9818(.A (n_325), .B (n_266), .Y (n_232));
  inv g9846(.A (n_394), .Y (PcSel[2]));
  inv g9848(.A (n_164), .Y (n_215));
  inv g9853(.A (n_143), .Y (n_218));
  nand2 g9765(.A (n_88), .B (\stateSub[2] ), .Y (n_142));
  nand2 g9784(.A (n_82), .B (\stateSub[1] ), .Y (n_141));
  nand3 g9792(.A (\state[0] ), .B (\stateSub[0] ), .C (n_101), .Y
       (n_140));
  nor2 g9795(.A (n_97), .B (n_138), .Y (n_139));
  nand2 g9796(.A (n_136), .B (n_132), .Y (n_137));
  nand2 g9799(.A (n_95), .B (n_156), .Y (n_135));
  nand3 g9806(.A (n_10), .B (n_112), .C (n_134), .Y (n_146));
  nand2 g9815(.A (\stateSub[0] ), .B (n_132), .Y (n_133));
  nand2 g9822(.A (n_132), .B (OpcodeCondIn[3]), .Y (n_131));
  nand2 g9837(.A (n_130), .B (n_152), .Y (n_297));
  inv g9838(.A (n_109), .Y (n_129));
  and2 g9840(.A (n_156), .B (n_236), .Y (n_244));
  nand2 g9847(.A (n_93), .B (\state[1] ), .Y (n_394));
  nand2 g9849(.A (n_293), .B (\stateSub[2] ), .Y (n_164));
  and2 g9852(.A (n_74), .B (n_156), .Y (n_159));
  nand2 g9854(.A (n_156), .B (OpcodeCondIn[3]), .Y (n_143));
  nand2 g9856(.A (n_130), .B (n_80), .Y (n_128));
  nand2 g9857(.A (n_130), .B (n_210), .Y (n_398));
  nand2 g9859(.A (n_130), .B (n_126), .Y (n_127));
  nand2 g9861(.A (n_130), .B (n_18), .Y (n_125));
  inv g9863(.A (n_124), .Y (n_165));
  nand2 g9874(.A (n_130), .B (n_241), .Y (n_123));
  nand2 g9876(.A (n_257), .B (\stateSub[1] ), .Y (n_122));
  nand2 g9864(.A (n_257), .B (n_241), .Y (n_124));
  nand2 g9858(.A (n_60), .B (\stateSub[2] ), .Y (n_121));
  nand2 g9791(.A (n_52), .B (n_119), .Y (n_120));
  nand2 g9794(.A (\state[0] ), .B (n_72), .Y (n_118));
  and2 g9774(.A (n_53), .B (n_162), .Y (n_207));
  nand3 g9813(.A (\state[0] ), .B (n_45), .C (n_170), .Y (n_117));
  and2 g9821(.A (n_51), .B (n_55), .Y (n_116));
  nor2 g9829(.A (n_319), .B (OpcodeCondIn[5]), .Y (n_115));
  inv g9831(.A (n_132), .Y (n_114));
  nor2 g9833(.A (n_112), .B (OpcodeCondIn[5]), .Y (n_113));
  inv g9834(.A (n_110), .Y (n_111));
  nor2 g9836(.A (n_162), .B (OpcodeCondIn[6]), .Y (n_216));
  nor2 g9839(.A (n_108), .B (n_64), .Y (n_109));
  and2 g9842(.A (n_257), .B (n_152), .Y (n_329));
  nand2 g9850(.A (n_90), .B (n_106), .Y (n_107));
  nor2 g9851(.A (n_106), .B (n_162), .Y (n_154));
  nand2 g9862(.A (n_70), .B (n_241), .Y (n_105));
  nand2 g9866(.A (n_257), .B (n_284), .Y (n_104));
  and2 g9867(.A (n_58), .B (n_103), .Y (n_300));
  nand2 g9868(.A (\state[0] ), .B (n_101), .Y (n_102));
  nand2 g9869(.A (\stateSub[2] ), .B (n_91), .Y (n_100));
  and2 g9871(.A (n_257), .B (n_210), .Y (n_325));
  nand2 g9872(.A (IRQ1), .B (n_512), .Y (n_99));
  nand2 g9873(.A (n_92), .B (\state[1] ), .Y (n_98));
  and2 g9875(.A (n_37), .B (n_217), .Y (n_97));
  nand2 g9877(.A (n_86), .B (n_210), .Y (n_96));
  nand2 g9879(.A (\stateSub[2] ), .B (n_94), .Y (n_95));
  inv g9910(.A (n_92), .Y (n_93));
  inv g9924(.A (n_91), .Y (n_156));
  inv g9926(.A (n_90), .Y (n_293));
  inv g9929(.A (n_89), .Y (n_130));
  nand2 g9835(.A (n_34), .B (n_296), .Y (n_110));
  nand3 g9812(.A (n_28), .B (n_210), .C (n_7), .Y (n_88));
  and2 g9860(.A (n_86), .B (n_241), .Y (IrWe));
  nand3 g9826(.A (n_180), .B (n_26), .C (n_84), .Y (n_85));
  nand2 g9827(.A (n_516), .B (IRQ2), .Y (n_83));
  nand2 g9828(.A (n_42), .B (n_69), .Y (n_82));
  nand2 g9830(.A (n_46), .B (n_80), .Y (n_81));
  nor2 g9832(.A (n_266), .B (n_217), .Y (n_132));
  nand3 g9845(.A (n_35), .B (n_36), .C (n_78), .Y (n_79));
  nand2 g9855(.A (n_86), .B (n_126), .Y (n_77));
  nand2 g9865(.A (n_86), .B (n_284), .Y (n_76));
  nand3 g9878(.A (n_74), .B (n_513), .C (OpcodeCondIn[2]), .Y (n_75));
  nand3 g9880(.A (OpcodeCondIn[6]), .B (n_84), .C (OpcodeCondIn[5]), .Y
       (n_73));
  xor2 g9882(.A (n_71), .B (OpcodeCondIn[0]), .Y (n_72));
  inv g9883(.A (n_69), .Y (n_70));
  nand2 g9889(.A (n_59), .B (n_14), .Y (n_67));
  nor2 g9890(.A (n_65), .B (OpcodeCondIn[7]), .Y (n_66));
  and2 g9892(.A (n_239), .B (n_63), .Y (n_64));
  inv g9893(.A (n_86), .Y (n_352));
  nand2 g9898(.A (n_236), .B (n_65), .Y (n_162));
  nand2 g9900(.A (n_284), .B (n_203), .Y (n_62));
  inv g9901(.A (n_106), .Y (n_257));
  nand2 g9927(.A (n_210), .B (n_61), .Y (n_90));
  nand2 g9906(.A (n_210), .B (n_40), .Y (n_60));
  nand2 g9911(.A (n_210), .B (n_59), .Y (n_92));
  nand2 g9914(.A (n_241), .B (n_23), .Y (n_58));
  nand2 g9916(.A (\state[0] ), .B (n_239), .Y (n_319));
  nor2 g9917(.A (n_239), .B (n_234), .Y (n_112));
  nand2 g9921(.A (n_288), .B (\stateSub[1] ), .Y (n_57));
  nand2 g9922(.A (n_65), .B (OpcodeCondIn[3]), .Y (n_101));
  nand2 g9923(.A (n_54), .B (nWait), .Y (n_56));
  nand2 g9925(.A (n_65), .B (OpcodeCondIn[6]), .Y (n_91));
  nand2 g9928(.A (n_210), .B (n_54), .Y (n_55));
  nand2 g9930(.A (n_54), .B (\state[1] ), .Y (n_89));
  and2 g9918(.A (n_234), .B (n_209), .Y (n_108));
  nor2 g9895(.A (n_74), .B (OpcodeCondIn[2]), .Y (n_138));
  nand4 g9825(.A (OpcodeCondIn[3]), .B (n_209), .C (n_134), .D
       (OpcodeCondIn[4]), .Y (n_53));
  nand2 g9841(.A (n_19), .B (n_11), .Y (n_52));
  nand3 g9843(.A (\stateSub[0] ), .B (n_50), .C (\state[1] ), .Y
       (n_51));
  nand3 g9870(.A (n_27), .B (n_119), .C (OpcodeCondIn[2]), .Y (n_49));
  nand3 g9881(.A (n_21), .B (\state[0] ), .C (OpcodeCondIn[5]), .Y
       (n_48));
  nand2 g9884(.A (n_119), .B (n_0), .Y (n_69));
  scandtype IRQ2_reg(.nReset (nReset), .Clock (Clock), .D (IRQ1), .Q
       (IRQ2), .nQ (n_512));
  nand2 g9887(.A (n_321), .B (n_152), .Y (n_47));
  nand2 g9891(.A (n_24), .B (n_50), .Y (n_46));
  nand2 g9888(.A (n_12), .B (n_9), .Y (n_45));
  nor2 g9894(.A (n_50), .B (\state[1] ), .Y (n_86));
  nand2 g9897(.A (\stateSub[1] ), .B (n_31), .Y (n_44));
  nand2 g9908(.A (n_136), .B (OpcodeCondIn[4]), .Y (n_43));
  nand2 g9903(.A (n_50), .B (\state[1] ), .Y (n_42));
  nand2 g9904(.A (n_241), .B (n_40), .Y (n_41));
  and2 g9909(.A (n_71), .B (OpcodeCondIn[0]), .Y (n_266));
  nand2 g9912(.A (n_126), .B (n_16), .Y (n_39));
  and2 g9913(.A (n_212), .B (n_217), .Y (n_94));
  nand2 g9915(.A (n_241), .B (OpcodeCondIn[6]), .Y (n_38));
  nand2 g9920(.A (n_29), .B (n_25), .Y (n_260));
  nand2 g9933(.A (n_36), .B (n_35), .Y (n_37));
  nand2 g9902(.A (n_61), .B (n_203), .Y (n_106));
  nand2 g9919(.A (n_22), .B (n_33), .Y (n_34));
  nand2 g9899(.A (\state[0] ), .B (n_31), .Y (n_32));
  nand2 g9896(.A (\stateSub[2] ), .B (n_31), .Y (n_30));
  inv g9961(.A (n_29), .Y (n_284));
  mux2 g9932(.S (OpcodeCondIn[6]), .I0 (n_296), .I1 (n_27), .Y (n_28));
  nand3 g9907(.A (OpcodeCondIn[3]), .B (n_236), .C (OpcodeCondIn[6]),
       .Y (n_26));
  inv g9963(.A (n_25), .Y (n_80));
  inv g9938(.A (n_31), .Y (n_65));
  inv g9940(.A (n_24), .Y (n_288));
  inv g9943(.A (n_321), .Y (n_23));
  inv g9947(.A (n_22), .Y (n_74));
  inv g9949(.A (n_33), .Y (n_78));
  inv g9972(.A (n_21), .Y (n_239));
  inv g9958(.A (n_180), .Y (n_20));
  inv g9955(.A (n_84), .Y (n_234));
  inv g9951(.A (n_50), .Y (n_54));
  inv g9967(.A (n_320), .Y (n_59));
  nand2 g9905(.A (n_18), .B (n_15), .Y (n_19));
  nand4 g9844(.A (OpcodeCondIn[3]), .B (n_236), .C (\stateSub[1] ), .D
       (OpcodeCondIn[6]), .Y (n_17));
  inv g9945(.A (n_126), .Y (n_210));
  nand2 g9937(.A (\StatusReg[2] ), .B (n_515), .Y (n_36));
  nand2 g9936(.A (\StatusReg[3] ), .B (n_514), .Y (n_35));
  nand2 g9965(.A (\state[0] ), .B (n_15), .Y (n_16));
  scandtype IRQ1_reg(.nReset (nReset), .Clock (Clock), .D (n_2), .Q
       (IRQ1), .nQ ());
  nand2 g9941(.A (n_203), .B (n_14), .Y (n_24));
  nand2 g9948(.A (n_13), .B (OpcodeCondIn[1]), .Y (n_22));
  nand2 g9952(.A (n_203), .B (n_40), .Y (n_50));
  nand2 g9942(.A (n_152), .B (n_134), .Y (n_12));
  nand2 g9946(.A (n_276), .B (n_152), .Y (n_126));
  inv g9978(.A (n_214), .Y (n_212));
  nand2 g9953(.A (n_27), .B (OpcodeCondIn[7]), .Y (n_11));
  inv g9980(.A (n_18), .Y (n_241));
  and2 g9957(.A (n_63), .B (OpcodeCondIn[3]), .Y (n_148));
  nand2 g9959(.A (n_15), .B (OpcodeCondIn[4]), .Y (n_180));
  nand2 g9968(.A (\stateSub[2] ), .B (n_40), .Y (n_320));
  nand2 g9971(.A (n_236), .B (OpcodeCondIn[4]), .Y (n_10));
  nor2 g9975(.A (n_40), .B (n_236), .Y (n_136));
  nand2 g9964(.A (\stateSub[0] ), .B (n_152), .Y (n_25));
  nand2 g9939(.A (n_63), .B (n_134), .Y (n_31));
  inv g9976(.A (n_9), .Y (n_209));
  nand2 g9956(.A (n_170), .B (OpcodeCondIn[4]), .Y (n_84));
  nand2 g9973(.A (n_15), .B (OpcodeCondIn[7]), .Y (n_21));
  nand2 g9962(.A (\stateSub[1] ), .B (n_276), .Y (n_29));
  nand3 g9931(.A (OpcodeCondIn[1]), .B (\StatusReg[0] ), .C
       (OpcodeCondIn[0]), .Y (n_8));
  nand2 g9970(.A (n_236), .B (OpcodeCondIn[6]), .Y (n_7));
  nand2 g9969(.A (\stateSub[1] ), .B (n_40), .Y (n_6));
  nor2 g9960(.A (\state[1] ), .B (n_40), .Y (n_61));
  nand2 g9950(.A (n_27), .B (OpcodeCondIn[0]), .Y (n_33));
  and2 g9966(.A (n_203), .B (\state[0] ), .Y (n_119));
  and2 g9954(.A (n_296), .B (OpcodeCondIn[1]), .Y (n_71));
  nand2 g9944(.A (n_14), .B (n_40), .Y (n_321));
  nand2 g9979(.A (OpcodeCondIn[3]), .B (OpcodeCondIn[2]), .Y (n_214));
  nand2 g9981(.A (\stateSub[1] ), .B (\stateSub[0] ), .Y (n_18));
  nor2 g9935(.A (OpcodeCondIn[0]), .B (OpcodeCondIn[1]), .Y (n_217));
  nand2 g9974(.A (\state[0] ), .B (\state[1] ), .Y (n_103));
  nand2 g9977(.A (OpcodeCondIn[7]), .B (OpcodeCondIn[6]), .Y (n_9));
  inv g9999(.A (OpcodeCondIn[3]), .Y (n_170));
  inv g9983(.A (OpcodeCondIn[4]), .Y (n_63));
  inv g9984(.A (OpcodeCondIn[6]), .Y (n_15));
  inv g9996(.A (OpcodeCondIn[1]), .Y (n_27));
  inv g9990(.A (nIRQ), .Y (n_2));
  inv g9995(.A (OpcodeCondIn[2]), .Y (n_296));
  inv g9985(.A (nWait), .Y (n_0));
  inv g9986(.A (OpcodeCondIn[5]), .Y (n_134));
  inv g9982(.A (OpcodeCondIn[0]), .Y (n_13));
  inv g9997(.A (OpcodeCondIn[7]), .Y (n_236));
endmodule

