
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

module control(ALE, AluEn, AluWe, AluOR, CFlag, ENB, ImmSel, IrWe,
     LrEn, LrSel, LrWe, MemEn, nME, nOE, nWE, Op1Sel, Op2Sel, PcEn,
     PcSel, PcWe, RegWe, Rs1Sel, RwSel, WdSel, StatusReg, StatusRegEn,
     SysBus, Clock, Flags, nIRQ, nReset, nWait, OpcodeCondIn);
 timeunit 1ns; timeprecision 100ps;
  input [3:0] SysBus, Flags;
  input Clock, nIRQ, nReset, nWait;
  input [7:0] OpcodeCondIn;
  output ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel,
       LrWe, MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel,
       StatusRegEn;
  output [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  output [2:0] PcSel;
  output [3:0] StatusReg;
  wire [3:0] SysBus, Flags;
  wire Clock, nIRQ, nReset, nWait;
  wire [7:0] OpcodeCondIn;
  wire ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel, LrWe,
       MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel,
       StatusRegEn;
  wire [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  wire [2:0] PcSel;
  wire [3:0] StatusReg;
  wire IRQ1, IRQ2, IntStatus, n_1, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_217, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_261;
  wire n_262, n_263, n_264, n_265, n_266, n_267, n_268, n_269;
  wire n_270, n_271, n_272, n_273, n_274, n_275, n_276, n_277;
  wire n_278, n_279, n_280, n_281, n_282, n_283, n_284, n_285;
  wire n_286, n_287, n_288, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_297, n_298, n_299, n_300, n_301, n_302, n_303;
  wire n_304, n_305, n_306, n_307, n_308, n_309, n_310, n_311;
  wire n_312, n_313, n_314, n_315, n_316, n_317, n_318, n_319;
  wire n_322, n_324, n_325, n_326, n_327, n_328, n_329, n_330;
  wire n_331, n_332, n_333, n_334, n_336, n_337, n_339, n_340;
  wire n_341, n_342, n_344, n_345, n_346, n_349, n_351, n_353;
  wire n_354, n_357, n_358, n_359, n_360, n_361, n_365, n_367;
  wire n_368, n_370, n_371, n_373, n_375, n_377, n_379, n_397;
  wire n_398, n_399, n_400, \stateSub[0] , \stateSub[1] , \stateSub[2]
       , \state[0] , \state[1] ;
  scandtype \state_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_379), .Q (\state[0] ), .nQ (n_63));
  nand4 g7975(.A (n_178), .B (n_307), .C (n_375), .D (n_377), .Y
       (RegWe));
  nand2 g7980(.A (n_370), .B (n_134), .Y (n_379));
  nand3 g7986(.A (n_156), .B (n_365), .C (n_377), .Y (Op2Sel[1]));
  nand3 g7993(.A (n_373), .B (n_361), .C (n_322), .Y (Rs1Sel[1]));
  nor2 g7998(.A (n_368), .B (n_326), .Y (n_375));
  scandtype \StatusReg_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_360), .Q (CFlag), .nQ ());
  scandtype \StatusReg_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_359), .Q (StatusReg[2]), .nQ (n_397));
  scandtype \StatusReg_reg[3] (.nReset (nReset), .Clock (Clock), .D
       (n_358), .Q (StatusReg[3]), .nQ (n_398));
  nand3 g7976(.A (n_373), .B (n_353), .C (n_371), .Y (AluEn));
  nand4 g8003(.A (n_371), .B (n_341), .C (n_344), .D (n_244), .Y
       (ImmSel));
  scandtype \StatusReg_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_367), .Q (StatusReg[0]), .nQ (n_399));
  nand2 g7994(.A (n_357), .B (\state[0] ), .Y (n_370));
  nand3 g8013(.A (n_233), .B (n_342), .C (n_277), .Y (Op2Sel[0]));
  nand4 g8018(.A (n_264), .B (n_250), .C (n_336), .D (n_160), .Y
       (n_368));
  nand3 g7981(.A (n_334), .B (n_311), .C (n_295), .Y (n_367));
  scandtype \stateSub_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_337), .Q (\stateSub[1] ), .nQ (n_123));
  nand4 g7979(.A (n_324), .B (n_371), .C (n_373), .D (n_170), .Y
       (AluWe));
  inv g8015(.A (n_351), .Y (n_365));
  nand4 g8006(.A (n_272), .B (n_302), .C (n_327), .D (n_88), .Y (PcEn));
  nand3 g8032(.A (n_252), .B (n_354), .C (n_349), .Y (PcSel[1]));
  nand4 g7977(.A (n_314), .B (n_172), .C (n_317), .D (n_346), .Y
       (Rs1Sel[0]));
  inv g8019(.A (n_345), .Y (n_361));
  nand3 g7982(.A (n_333), .B (n_310), .C (n_294), .Y (n_360));
  nand3 g7983(.A (n_331), .B (n_306), .C (n_292), .Y (n_359));
  nand3 g7984(.A (n_330), .B (n_305), .C (n_291), .Y (n_358));
  nand3 g8002(.A (n_284), .B (n_318), .C (\stateSub[0] ), .Y (n_357));
  inv g8046(.A (n_339), .Y (LrWe));
  scanreg IntStatus_reg(.nReset (nReset), .Clock (Clock), .D (n_281),
       .Load (n_265), .Q (IntStatus), .nQ ());
  nand2 g8057(.A (n_354), .B (n_228), .Y (LrEn));
  nor2 g7988(.A (n_300), .B (Op1Sel), .Y (n_353));
  nand4 g8016(.A (n_154), .B (n_227), .C (n_312), .D (n_299), .Y
       (n_351));
  nand2 g8001(.A (n_328), .B (n_349), .Y (PcSel[0]));
  nand3 g8012(.A (n_237), .B (n_373), .C (n_325), .Y (RwSel[1]));
  nand4 g7995(.A (n_346), .B (n_164), .C (n_301), .D (\stateSub[1] ),
       .Y (RwSel[0]));
  nand4 g8020(.A (n_316), .B (n_247), .C (n_230), .D (n_185), .Y
       (n_345));
  nor2 g8021(.A (n_329), .B (n_149), .Y (n_344));
  nand4 g8010(.A (n_181), .B (n_242), .C (n_304), .D (n_349), .Y
       (PcWe));
  nand2 g8040(.A (n_340), .B (n_202), .Y (n_342));
  nand2 g8043(.A (n_340), .B (OpcodeCondIn[5]), .Y (n_341));
  nor2 g8047(.A (LrSel), .B (n_213), .Y (n_339));
  nand4 g7987(.A (n_197), .B (n_85), .C (n_285), .D (n_7), .Y (n_337));
  nor2 g8049(.A (n_308), .B (n_248), .Y (n_336));
  scandtype \stateSub_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_315), .Q (\stateSub[2] ), .nQ (n_234));
  nand3 g8033(.A (n_51), .B (n_235), .C (n_297), .Y (nWE));
  nand2 g8027(.A (n_332), .B (Flags[0]), .Y (n_334));
  nand2 g8028(.A (n_332), .B (Flags[1]), .Y (n_333));
  nand2 g8029(.A (n_332), .B (Flags[2]), .Y (n_331));
  nand2 g8030(.A (n_332), .B (Flags[3]), .Y (n_330));
  nor2 g8041(.A (n_286), .B (n_166), .Y (n_329));
  nand2 g8007(.A (n_273), .B (n_319), .Y (n_328));
  inv g8044(.A (n_332), .Y (n_327));
  inv g8054(.A (n_325), .Y (n_326));
  nand2 g8011(.A (n_282), .B (n_245), .Y (n_324));
  scandtype \state_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_298), .Q (\state[1] ), .nQ (n_258));
  nand4 g8022(.A (n_322), .B (n_270), .C (n_288), .D (n_377), .Y
       (AluOR[1]));
  nand2 g8008(.A (n_283), .B (n_84), .Y (nME));
  nand4 g8017(.A (n_140), .B (n_208), .C (n_274), .D (n_50), .Y (nOE));
  nand2 g8069(.A (n_319), .B (n_151), .Y (n_354));
  and2 g8079(.A (n_319), .B (n_68), .Y (Op1Sel));
  nand2 g8031(.A (\stateSub[2] ), .B (n_287), .Y (n_318));
  nor2 g8000(.A (n_290), .B (n_209), .Y (n_317));
  nand2 g8042(.A (n_313), .B (\stateSub[0] ), .Y (n_316));
  nand3 g8045(.A (n_279), .B (n_203), .C (n_182), .Y (n_332));
  nand4 g8009(.A (n_314), .B (n_255), .C (n_194), .D (n_60), .Y
       (n_315));
  nand2 g8055(.A (n_313), .B (n_268), .Y (n_325));
  nor2 g8056(.A (n_222), .B (n_275), .Y (n_312));
  nand2 g7989(.A (n_309), .B (StatusReg[0]), .Y (n_311));
  nand2 g7990(.A (n_309), .B (CFlag), .Y (n_310));
  nor2 g8070(.A (n_303), .B (OpcodeCondIn[5]), .Y (n_308));
  inv g8071(.A (n_307), .Y (n_340));
  nand2 g7991(.A (n_309), .B (StatusReg[2]), .Y (n_306));
  nand2 g7992(.A (n_309), .B (StatusReg[3]), .Y (n_305));
  nor2 g8081(.A (n_400), .B (n_102), .Y (LrSel));
  and2 g8085(.A (n_303), .B (n_141), .Y (n_304));
  and2 g8094(.A (n_276), .B (n_116), .Y (n_302));
  inv g8036(.A (n_280), .Y (n_301));
  nand4 g8004(.A (n_187), .B (n_201), .C (n_239), .D (n_299), .Y
       (n_300));
  nand3 g8005(.A (n_105), .B (n_206), .C (n_11), .Y (n_298));
  nand3 g8048(.A (n_258), .B (n_234), .C (n_271), .Y (n_297));
  inv g8130(.A (n_400), .Y (n_319));
  nand2 g8050(.A (n_293), .B (SysBus[0]), .Y (n_295));
  nand2 g8051(.A (n_293), .B (SysBus[1]), .Y (n_294));
  nand2 g8052(.A (n_293), .B (SysBus[2]), .Y (n_292));
  nand2 g8053(.A (n_293), .B (SysBus[3]), .Y (n_291));
  nand4 g8014(.A (n_31), .B (n_109), .C (n_207), .D (n_115), .Y
       (n_290));
  nand3 g8064(.A (n_322), .B (n_288), .C (n_377), .Y (AluOR[0]));
  nand2 g8062(.A (n_192), .B (n_246), .Y (ENB));
  nand3 g8065(.A (n_147), .B (n_225), .C (n_266), .Y (n_287));
  nor2 g8067(.A (n_221), .B (n_238), .Y (n_286));
  nand3 g8072(.A (n_169), .B (n_278), .C (n_257), .Y (n_307));
  nand2 g8024(.A (n_256), .B (n_284), .Y (n_285));
  nand2 g8025(.A (n_254), .B (\state[0] ), .Y (n_283));
  nand2 g8026(.A (n_259), .B (n_146), .Y (n_282));
  and2 g8093(.A (n_262), .B (n_180), .Y (n_371));
  nand4 g8034(.A (n_236), .B (n_346), .C (n_118), .D (\stateSub[1] ),
       .Y (n_281));
  and2 g8099(.A (n_261), .B (n_377), .Y (n_373));
  nand4 g8037(.A (n_89), .B (n_18), .C (n_210), .D (n_12), .Y (n_280));
  nand2 g8126(.A (n_278), .B (n_48), .Y (n_279));
  nand2 g8128(.A (n_278), .B (n_29), .Y (n_303));
  nand2 g8142(.A (n_278), .B (n_132), .Y (n_277));
  nand3 g8147(.A (n_241), .B (n_263), .C (n_231), .Y (n_276));
  and2 g8074(.A (n_269), .B (\stateSub[0] ), .Y (n_275));
  nand2 g8084(.A (n_223), .B (n_184), .Y (n_274));
  nand4 g8023(.A (n_46), .B (n_8), .C (n_176), .D (n_75), .Y (n_273));
  and2 g8086(.A (n_267), .B (n_220), .Y (n_313));
  nand2 g8087(.A (n_100), .B (n_271), .Y (n_272));
  nand2 g8095(.A (n_269), .B (n_268), .Y (n_270));
  nand4 g7999(.A (n_267), .B (n_117), .C (n_183), .D (n_266), .Y
       (n_309));
  nand2 g8096(.A (n_205), .B (n_377), .Y (n_265));
  nand2 g8122(.A (n_263), .B (OpcodeCondIn[5]), .Y (n_264));
  nand2 g8123(.A (n_260), .B (n_153), .Y (n_262));
  nand2 g8143(.A (n_260), .B (n_219), .Y (n_261));
  nand4 g8058(.A (n_161), .B (n_258), .C (\state[0] ), .D (n_257), .Y
       (n_259));
  scandtype \stateSub_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_171), .Q (n_114), .nQ (\stateSub[0] ));
  nand2 g8060(.A (n_158), .B (n_174), .Y (n_256));
  and2 g8061(.A (n_125), .B (n_175), .Y (n_255));
  nand3 g8063(.A (n_121), .B (n_163), .C (n_70), .Y (n_254));
  nand2 g8078(.A (n_124), .B (n_196), .Y (ALE));
  nand2 g8068(.A (n_251), .B (n_249), .Y (n_252));
  and2 g8082(.A (n_251), .B (OpcodeCondIn[2]), .Y (n_293));
  nand4 g8088(.A (n_249), .B (n_243), .C (n_157), .D (nWait), .Y
       (n_250));
  and2 g8089(.A (n_240), .B (n_199), .Y (n_248));
  nand2 g8091(.A (n_186), .B (n_190), .Y (n_247));
  nand2 g8098(.A (n_198), .B (n_245), .Y (n_246));
  nand3 g8101(.A (\stateSub[0] ), .B (n_267), .C (n_243), .Y (n_244));
  nand3 g8102(.A (n_241), .B (n_240), .C (n_177), .Y (n_242));
  nand3 g8105(.A (n_232), .B (n_240), .C (OpcodeCondIn[5]), .Y (n_239));
  nor2 g8106(.A (n_214), .B (n_92), .Y (n_238));
  nand2 g8110(.A (n_260), .B (n_257), .Y (n_237));
  nand2 g8112(.A (n_224), .B (n_126), .Y (n_271));
  nand2 g8114(.A (n_258), .B (n_152), .Y (n_236));
  nand3 g8116(.A (n_234), .B (n_139), .C (n_195), .Y (n_235));
  nand3 g8119(.A (n_232), .B (n_229), .C (n_231), .Y (n_233));
  nand3 g8121(.A (n_179), .B (n_229), .C (OpcodeCondIn[3]), .Y (n_230));
  nand2 g8124(.A (n_226), .B (n_215), .Y (n_228));
  nand2 g8125(.A (n_226), .B (n_211), .Y (n_227));
  nand2 g8127(.A (n_150), .B (n_128), .Y (n_225));
  nor2 g8129(.A (n_101), .B (n_224), .Y (n_269));
  nand2 g8140(.A (n_217), .B (n_97), .Y (n_223));
  and2 g8141(.A (n_229), .B (n_243), .Y (n_222));
  and2 g8145(.A (n_240), .B (OpcodeCondIn[7]), .Y (n_221));
  nand2 g8146(.A (n_189), .B (n_224), .Y (n_220));
  nand3 g8151(.A (n_204), .B (n_229), .C (n_219), .Y (n_288));
  nor2 g8133(.A (n_217), .B (n_188), .Y (StatusRegEn));
  nor2 g8076(.A (n_212), .B (n_215), .Y (WdSel));
  inv g8172(.A (n_214), .Y (n_278));
  nor2 g8073(.A (n_212), .B (n_211), .Y (n_213));
  nor2 g8075(.A (n_91), .B (n_168), .Y (n_210));
  and2 g8077(.A (n_167), .B (n_258), .Y (n_209));
  nand3 g8090(.A (n_234), .B (n_200), .C (n_258), .Y (n_208));
  nand2 g8092(.A (n_165), .B (\stateSub[1] ), .Y (n_207));
  nand4 g8035(.A (\stateSub[1] ), .B (\state[0] ), .C (n_148), .D
       (n_193), .Y (n_206));
  nand3 g8150(.A (n_204), .B (n_229), .C (n_241), .Y (n_205));
  nand3 g8109(.A (n_232), .B (n_229), .C (n_202), .Y (n_203));
  nand4 g8039(.A (n_258), .B (n_234), .C (n_200), .D (n_211), .Y
       (n_201));
  nand3 g8111(.A (n_71), .B (n_120), .C (n_202), .Y (n_199));
  nand2 g8115(.A (n_197), .B (n_143), .Y (n_198));
  nand2 g8117(.A (n_98), .B (n_195), .Y (n_196));
  nand2 g8118(.A (n_142), .B (n_193), .Y (n_194));
  nand2 g8134(.A (n_191), .B (n_284), .Y (n_192));
  and2 g8135(.A (n_191), .B (n_267), .Y (n_251));
  nand2 g8136(.A (n_189), .B (n_188), .Y (n_190));
  nand2 g8137(.A (n_186), .B (n_195), .Y (n_187));
  nand3 g8148(.A (n_268), .B (n_145), .C (n_184), .Y (n_185));
  and2 g8059(.A (n_129), .B (n_137), .Y (n_183));
  nand2 g8154(.A (n_229), .B (n_93), .Y (n_182));
  nand2 g8167(.A (n_229), .B (n_36), .Y (n_181));
  nand2 g8173(.A (n_229), .B (OpcodeCondIn[4]), .Y (n_214));
  and2 g8177(.A (n_229), .B (n_184), .Y (n_260));
  nand2 g8178(.A (n_229), .B (n_179), .Y (n_180));
  nand2 g8179(.A (n_229), .B (n_232), .Y (n_178));
  and2 g8183(.A (n_229), .B (n_177), .Y (n_263));
  nor2 g8080(.A (n_135), .B (n_83), .Y (n_176));
  nand2 g8083(.A (n_106), .B (n_173), .Y (n_175));
  nand2 g8100(.A (\stateSub[2] ), .B (n_173), .Y (n_174));
  nand4 g8103(.A (n_202), .B (n_162), .C (n_284), .D (OpcodeCondIn[7]),
       .Y (n_172));
  nand3 g8104(.A (n_37), .B (n_130), .C (n_62), .Y (n_171));
  nand3 g8108(.A (n_245), .B (n_155), .C (n_169), .Y (n_170));
  and2 g8113(.A (n_258), .B (n_131), .Y (n_168));
  nand2 g8138(.A (n_127), .B (n_166), .Y (n_167));
  nand3 g8149(.A (n_245), .B (n_267), .C (n_159), .Y (n_212));
  nand3 g8153(.A (n_20), .B (n_164), .C (n_108), .Y (n_165));
  nand3 g8152(.A (n_162), .B (\stateSub[1] ), .C (OpcodeCondIn[7]), .Y
       (n_163));
  nor2 g8155(.A (n_136), .B (OpcodeCondIn[4]), .Y (n_240));
  and2 g8156(.A (n_184), .B (n_249), .Y (n_161));
  nand4 g8066(.A (n_159), .B (n_245), .C (n_267), .D (n_169), .Y
       (n_160));
  nand2 g8162(.A (n_122), .B (n_193), .Y (n_158));
  nand2 g8163(.A (n_157), .B (n_219), .Y (n_217));
  nand2 g8166(.A (n_155), .B (n_245), .Y (n_156));
  nand2 g8169(.A (n_186), .B (n_204), .Y (n_154));
  nand2 g8170(.A (n_204), .B (n_153), .Y (n_224));
  nand2 g8171(.A (n_151), .B (n_204), .Y (n_152));
  and2 g8174(.A (n_157), .B (n_144), .Y (n_226));
  nand2 g8180(.A (n_162), .B (OpcodeCondIn[3]), .Y (n_150));
  inv g8184(.A (n_189), .Y (n_243));
  and2 g8188(.A (n_155), .B (n_268), .Y (n_149));
  nand2 g8120(.A (n_28), .B (n_111), .Y (n_148));
  nand2 g8132(.A (n_147), .B (n_103), .Y (n_173));
  nand2 g8159(.A (n_145), .B (n_144), .Y (n_146));
  nand2 g8165(.A (n_284), .B (n_159), .Y (n_143));
  nor2 g8168(.A (n_74), .B (n_188), .Y (n_191));
  and2 g8175(.A (\state[0] ), .B (n_144), .Y (n_200));
  nand2 g8176(.A (n_99), .B (n_107), .Y (n_142));
  nand2 g8182(.A (n_119), .B (n_266), .Y (n_195));
  nand2 g8185(.A (n_159), .B (OpcodeCondIn[3]), .Y (n_189));
  nand3 g8218(.A (n_245), .B (n_267), .C (nWait), .Y (n_141));
  nand3 g8220(.A (n_234), .B (n_139), .C (n_179), .Y (n_140));
  nand3 g8221(.A (\state[1] ), .B (n_133), .C (n_123), .Y (n_322));
  inv g8223(.A (n_349), .Y (PcSel[2]));
  nand2 g8097(.A (n_113), .B (OpcodeCondIn[7]), .Y (n_137));
  inv g8229(.A (n_136), .Y (n_229));
  nor2 g8107(.A (n_110), .B (OpcodeCondIn[1]), .Y (n_135));
  nand2 g8225(.A (n_133), .B (n_284), .Y (n_134));
  nand2 g8158(.A (n_86), .B (n_39), .Y (n_132));
  nand2 g8160(.A (n_76), .B (n_95), .Y (n_131));
  nand2 g8181(.A (n_90), .B (n_114), .Y (n_130));
  nand2 g8187(.A (n_87), .B (n_128), .Y (n_129));
  mux2 g8190(.S (n_202), .I0 (OpcodeCondIn[7]), .I1 (n_64), .Y (n_127));
  nor2 g8197(.A (n_219), .B (n_153), .Y (n_162));
  inv g8198(.A (n_159), .Y (n_126));
  nand2 g8201(.A (n_82), .B (\stateSub[0] ), .Y (n_125));
  nand2 g8204(.A (n_133), .B (n_123), .Y (n_124));
  and2 g8206(.A (n_267), .B (n_234), .Y (n_157));
  nand2 g8209(.A (\stateSub[2] ), .B (n_121), .Y (n_122));
  nand2 g8214(.A (n_219), .B (n_19), .Y (n_120));
  inv g8216(.A (n_119), .Y (n_184));
  and2 g8219(.A (n_145), .B (n_179), .Y (n_155));
  nand2 g8224(.A (n_133), .B (n_67), .Y (n_349));
  nand2 g8230(.A (n_267), .B (n_118), .Y (n_136));
  inv g8231(.A (n_104), .Y (n_117));
  inv g8233(.A (n_188), .Y (n_204));
  nand2 g8241(.A (n_133), .B (\stateSub[1] ), .Y (n_116));
  nand2 g8139(.A (n_72), .B (n_114), .Y (n_115));
  nand2 g8144(.A (n_73), .B (n_26), .Y (n_113));
  nor2 g8210(.A (n_77), .B (n_197), .Y (IrWe));
  nand2 g8157(.A (\stateSub[0] ), .B (n_66), .Y (n_111));
  and2 g8186(.A (n_69), .B (OpcodeCondIn[2]), .Y (n_110));
  nor2 g8199(.A (n_266), .B (OpcodeCondIn[6]), .Y (n_159));
  and2 g8202(.A (n_145), .B (n_234), .Y (n_186));
  and2 g8205(.A (n_128), .B (n_257), .Y (n_144));
  nor2 g8207(.A (n_57), .B (n_61), .Y (n_109));
  nand2 g8208(.A (n_234), .B (n_94), .Y (n_108));
  nand2 g8212(.A (n_106), .B (n_96), .Y (n_107));
  nand2 g8217(.A (n_128), .B (OpcodeCondIn[3]), .Y (n_119));
  nand2 g8222(.A (n_81), .B (\state[1] ), .Y (n_105));
  nor2 g8232(.A (n_118), .B (n_128), .Y (n_104));
  nand2 g8234(.A (n_128), .B (n_177), .Y (n_188));
  nand2 g8226(.A (n_79), .B (n_128), .Y (n_103));
  inv g8268(.A (n_102), .Y (n_219));
  inv g8278(.A (n_101), .Y (n_267));
  inv g8280(.A (n_99), .Y (n_100));
  inv g8289(.A (n_97), .Y (n_98));
  inv g8293(.A (n_96), .Y (n_121));
  inv g8287(.A (n_94), .Y (n_95));
  nand2 g8191(.A (n_41), .B (n_44), .Y (n_93));
  nor2 g8192(.A (n_42), .B (OpcodeCondIn[3]), .Y (n_92));
  nor2 g8196(.A (n_38), .B (n_32), .Y (n_164));
  nor2 g8200(.A (n_35), .B (\stateSub[2] ), .Y (n_91));
  nand2 g8203(.A (n_52), .B (n_234), .Y (n_90));
  nand2 g8211(.A (n_106), .B (n_49), .Y (n_89));
  nand2 g8213(.A (n_78), .B (n_34), .Y (n_88));
  nand3 g8215(.A (n_153), .B (n_245), .C (n_215), .Y (n_87));
  nand2 g8227(.A (n_53), .B (OpcodeCondIn[5]), .Y (n_86));
  nor2 g8237(.A (n_84), .B (n_59), .Y (n_85));
  and2 g8238(.A (IntStatus), .B (IRQ2), .Y (n_193));
  and2 g8239(.A (n_56), .B (n_153), .Y (n_83));
  inv g8253(.A (n_197), .Y (n_82));
  inv g8257(.A (n_266), .Y (n_179));
  inv g8260(.A (n_81), .Y (n_133));
  nand2 g8269(.A (n_27), .B (OpcodeCondIn[1]), .Y (n_102));
  nand3 g8273(.A (\state[1] ), .B (n_78), .C (n_123), .Y (n_299));
  nand2 g8277(.A (n_245), .B (nWait), .Y (n_77));
  nand2 g8281(.A (n_268), .B (n_284), .Y (n_99));
  and2 g8291(.A (n_231), .B (OpcodeCondIn[6]), .Y (n_128));
  and2 g8292(.A (n_139), .B (\state[0] ), .Y (n_145));
  nand2 g8294(.A (n_65), .B (n_231), .Y (n_96));
  nand3 g8242(.A (OpcodeCondIn[7]), .B (n_75), .C (OpcodeCondIn[1]), .Y
       (n_76));
  nand2 g8258(.A (n_257), .B (n_231), .Y (n_266));
  nand2 g8279(.A (n_284), .B (\state[0] ), .Y (n_101));
  nand2 g8276(.A (n_245), .B (n_153), .Y (n_74));
  nand3 g8161(.A (OpcodeCondIn[4]), .B (n_47), .C (OpcodeCondIn[6]), .Y
       (n_73));
  nand3 g8164(.A (n_71), .B (n_258), .C (n_70), .Y (n_72));
  nand4 g8189(.A (OpcodeCondIn[6]), .B (n_177), .C (n_202), .D
       (OpcodeCondIn[4]), .Y (n_147));
  nand3 g8193(.A (n_54), .B (n_55), .C (OpcodeCondIn[0]), .Y (n_69));
  inv g8194(.A (n_68), .Y (n_241));
  nand2 g8290(.A (n_268), .B (n_139), .Y (n_97));
  nand2 g8288(.A (n_231), .B (OpcodeCondIn[3]), .Y (n_94));
  nand3 g8236(.A (n_67), .B (n_118), .C (n_63), .Y (n_377));
  nand3 g8240(.A (n_30), .B (n_65), .C (n_202), .Y (n_66));
  nor2 g8248(.A (n_13), .B (n_232), .Y (n_64));
  nand2 g8254(.A (n_284), .B (n_63), .Y (n_197));
  nand2 g8255(.A (n_139), .B (n_234), .Y (n_62));
  and2 g8256(.A (n_139), .B (n_40), .Y (n_61));
  nand2 g8261(.A (n_268), .B (n_63), .Y (n_81));
  nand2 g8270(.A (n_58), .B (\stateSub[2] ), .Y (n_60));
  and2 g8274(.A (n_67), .B (\state[0] ), .Y (n_59));
  nor2 g8275(.A (n_21), .B (n_58), .Y (n_84));
  and2 g8262(.A (n_67), .B (n_234), .Y (n_57));
  nand2 g8302(.A (n_55), .B (n_54), .Y (n_56));
  nand2 g8295(.A (n_10), .B (n_65), .Y (n_53));
  nor2 g8298(.A (n_58), .B (n_5), .Y (n_52));
  nor2 g8299(.A (n_58), .B (n_16), .Y (n_346));
  nand2 g8282(.A (n_78), .B (n_33), .Y (n_51));
  and2 g8249(.A (n_45), .B (n_249), .Y (n_151));
  nand2 g8285(.A (n_78), .B (n_22), .Y (n_50));
  nand2 g8195(.A (n_249), .B (n_17), .Y (n_68));
  nand2 g8272(.A (n_15), .B (OpcodeCondIn[6]), .Y (n_49));
  nand2 g8228(.A (n_47), .B (OpcodeCondIn[6]), .Y (n_48));
  nand3 g8235(.A (n_45), .B (n_399), .C (OpcodeCondIn[2]), .Y (n_46));
  nand2 g8245(.A (n_43), .B (n_25), .Y (n_44));
  scandtype IRQ2_reg(.nReset (nReset), .Clock (Clock), .D (IRQ1), .Q
       (IRQ2), .nQ ());
  nor2 g8246(.A (n_75), .B (OpcodeCondIn[1]), .Y (n_42));
  nand2 g8247(.A (n_40), .B (n_257), .Y (n_41));
  nand2 g8250(.A (n_24), .B (n_177), .Y (n_39));
  nor2 g8252(.A (n_9), .B (OpcodeCondIn[7]), .Y (n_38));
  nand2 g8259(.A (n_78), .B (n_123), .Y (n_37));
  nand2 g8263(.A (n_65), .B (n_202), .Y (n_36));
  and2 g8264(.A (n_258), .B (n_65), .Y (n_35));
  nand2 g8265(.A (n_33), .B (n_23), .Y (n_34));
  nor2 g8244(.A (\stateSub[0] ), .B (n_6), .Y (n_32));
  nand2 g8284(.A (n_4), .B (\stateSub[2] ), .Y (n_314));
  nand3 g8296(.A (OpcodeCondIn[7]), .B (n_258), .C (OpcodeCondIn[4]),
       .Y (n_31));
  inv g8327(.A (n_70), .Y (n_79));
  nand2 g8283(.A (n_29), .B (OpcodeCondIn[4]), .Y (n_30));
  inv g8309(.A (n_40), .Y (n_231));
  inv g8317(.A (n_28), .Y (n_268));
  inv g8319(.A (n_75), .Y (n_27));
  nand3 g8286(.A (n_25), .B (n_24), .C (OpcodeCondIn[5]), .Y (n_26));
  inv g8311(.A (n_23), .Y (n_139));
  inv g8324(.A (n_22), .Y (n_284));
  inv g8331(.A (n_21), .Y (n_245));
  inv g8329(.A (n_65), .Y (n_232));
  nand3 g8266(.A (OpcodeCondIn[1]), .B (n_234), .C (OpcodeCondIn[6]),
       .Y (n_20));
  nand2 g8251(.A (n_257), .B (n_19), .Y (n_71));
  nand3 g8267(.A (OpcodeCondIn[0]), .B (n_234), .C (OpcodeCondIn[6]),
       .Y (n_18));
  nor2 g8334(.A (n_234), .B (\state[1] ), .Y (n_106));
  nand2 g8320(.A (n_249), .B (OpcodeCondIn[0]), .Y (n_75));
  nor2 g8336(.A (n_63), .B (n_258), .Y (n_58));
  xor2 g8301(.A (OpcodeCondIn[5]), .B (OpcodeCondIn[3]), .Y (n_47));
  xor2 g8300(.A (OpcodeCondIn[1]), .B (OpcodeCondIn[0]), .Y (n_17));
  nand2 g8306(.A (StatusReg[3]), .B (n_397), .Y (n_54));
  nand2 g8310(.A (n_202), .B (n_25), .Y (n_40));
  and2 g8313(.A (n_63), .B (n_258), .Y (n_16));
  and2 g8315(.A (n_234), .B (n_63), .Y (n_78));
  nand2 g8330(.A (n_24), .B (OpcodeCondIn[7]), .Y (n_65));
  nor2 g8316(.A (n_14), .B (OpcodeCondIn[0]), .Y (n_45));
  nand2 g8321(.A (n_14), .B (OpcodeCondIn[7]), .Y (n_15));
  nor2 g8333(.A (n_114), .B (n_234), .Y (n_118));
  nand2 g8325(.A (\stateSub[1] ), .B (n_258), .Y (n_22));
  inv g8339(.A (n_29), .Y (n_177));
  and2 g8314(.A (\stateSub[0] ), .B (n_169), .Y (n_13));
  inv g8343(.A (n_33), .Y (n_67));
  inv g8346(.A (n_166), .Y (n_43));
  nand2 g8338(.A (\stateSub[2] ), .B (n_114), .Y (n_12));
  nand2 g8318(.A (n_234), .B (\stateSub[0] ), .Y (n_28));
  nand2 g8332(.A (n_114), .B (n_234), .Y (n_21));
  nand2 g8305(.A (StatusReg[2]), .B (n_398), .Y (n_55));
  nand2 g8326(.A (\state[1] ), .B (n_123), .Y (n_11));
  nand2 g8323(.A (n_24), .B (OpcodeCondIn[3]), .Y (n_10));
  nand2 g8328(.A (n_169), .B (OpcodeCondIn[7]), .Y (n_70));
  inv g8341(.A (n_211), .Y (n_215));
  nand2 g8312(.A (n_123), .B (n_258), .Y (n_23));
  nand2 g8335(.A (n_234), .B (OpcodeCondIn[6]), .Y (n_9));
  scandtype IRQ1_reg(.nReset (nReset), .Clock (Clock), .D (n_1), .Q
       (IRQ1), .nQ ());
  nand3 g8297(.A (OpcodeCondIn[1]), .B (StatusReg[0]), .C
       (OpcodeCondIn[0]), .Y (n_8));
  nand2 g8337(.A (n_114), .B (\stateSub[1] ), .Y (n_7));
  nand2 g8347(.A (OpcodeCondIn[6]), .B (OpcodeCondIn[5]), .Y (n_166));
  nor2 g8307(.A (OpcodeCondIn[0]), .B (OpcodeCondIn[1]), .Y (n_153));
  nand2 g8340(.A (OpcodeCondIn[7]), .B (OpcodeCondIn[3]), .Y (n_29));
  nand2 g8342(.A (OpcodeCondIn[3]), .B (OpcodeCondIn[2]), .Y (n_211));
  nor2 g8308(.A (OpcodeCondIn[6]), .B (OpcodeCondIn[2]), .Y (n_6));
  nand2 g8344(.A (\state[1] ), .B (\stateSub[1] ), .Y (n_33));
  nor2 g8304(.A (\state[1] ), .B (nWait), .Y (n_5));
  nand2 g8322(.A (\stateSub[0] ), .B (\stateSub[1] ), .Y (n_4));
  and2 g8345(.A (OpcodeCondIn[6]), .B (OpcodeCondIn[3]), .Y (n_19));
  inv g8362(.A (OpcodeCondIn[1]), .Y (n_14));
  inv g8351(.A (OpcodeCondIn[7]), .Y (n_257));
  inv g8352(.A (OpcodeCondIn[5]), .Y (n_202));
  inv g8363(.A (OpcodeCondIn[3]), .Y (n_169));
  inv g8358(.A (OpcodeCondIn[4]), .Y (n_25));
  inv g8357(.A (OpcodeCondIn[2]), .Y (n_249));
  inv g8360(.A (nIRQ), .Y (n_1));
  inv g8355(.A (OpcodeCondIn[6]), .Y (n_24));
  nand3 g2(.A (n_278), .B (n_79), .C (n_43), .Y (n_400));
  buffer rm_assigns_buf_MemEn(.A (ENB), .Y (MemEn));
  buffer rm_assigns_buf_StatusReg_1(.A (CFlag), .Y (StatusReg[1]));
endmodule

