timeunit 10ns; timeprecision 100ps;

// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

module control(ALE, AluEn, AluWe, AluOR, CFlag, ENB, ImmSel, IrWe,
     LrEn, LrSel, LrWe, MemEn, nME, nOE, nWE, Op1Sel, Op2Sel, PcEn,
     PcSel, PcWe, RegWe, Rs1Sel, RwSel, WdSel, SysBus, Clock, Flags,
     nIRQ, nReset, nWait, OpcodeCondIn);
  input Clock, nIRQ, nReset, nWait;
  input [3:0] Flags;
  input [7:0] OpcodeCondIn;
  output ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel,
       LrWe, MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel;
  output [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  output [2:0] PcSel;
  inout [15:0] SysBus;
  wire Clock, nIRQ, nReset, nWait;
  wire [3:0] Flags;
  wire [7:0] OpcodeCondIn;
  wire ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel, LrWe,
       MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel;
  wire [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  wire [2:0] PcSel;
  wire [15:0] SysBus;
  wire IRQ1, IRQ2, InISR, IntReq, \StatusReg[0] , \StatusReg[2] ,
       \StatusReg[3] , n_3;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_236, n_237, n_238, n_239, n_240, n_241, n_242;
  wire n_243, n_244, n_245, n_246, n_247, n_248, n_249, n_250;
  wire n_251, n_252, n_253, n_254, n_255, n_256, n_257, n_258;
  wire n_259, n_260, n_261, n_262, n_263, n_264, n_265, n_266;
  wire n_267, n_268, n_269, n_270, n_272, n_273, n_274, n_275;
  wire n_276, n_277, n_278, n_279, n_280, n_282, n_283, n_284;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_293;
  wire n_298, n_300, n_302, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_320, n_321, n_323, n_324, n_326, n_327;
  wire n_328, n_329, n_330, n_331, n_334, n_335, n_336, n_338;
  wire n_340, n_341, n_343, n_344, n_345, n_347, n_348, n_351;
  wire n_352, n_353, n_354, n_355, n_359, n_360, n_361, n_362;
  wire n_363, n_367, n_368, n_473, n_474, n_475, n_476, n_477;
  wire n_478, n_479, \stateSub[0] , \stateSub[1] , \stateSub[2] ,
       \state[0] , \state[1] ;
  scandtype \StatusReg_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_360), .Q (\StatusReg[0] ), .nQ (n_477));
  scandtype \StatusReg_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_361), .Q (CFlag), .nQ ());
  scandtype \StatusReg_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_367), .Q (\StatusReg[2] ), .nQ (n_474));
  scandtype \StatusReg_reg[3] (.nReset (nReset), .Clock (Clock), .D
       (n_368), .Q (\StatusReg[3] ), .nQ (n_475));
  nand3 g7920(.A (n_362), .B (n_355), .C (n_328), .Y (Op2Sel[1]));
  scandtype \stateSub_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_359), .Q (\stateSub[1] ), .nQ (n_163));
  nand3 g7916(.A (n_305), .B (n_345), .C (n_311), .Y (n_368));
  nand3 g7915(.A (n_306), .B (n_347), .C (n_313), .Y (n_367));
  nand4 g7912(.A (n_275), .B (n_298), .C (n_343), .D (n_363), .Y
       (AluEn));
  nand4 g7911(.A (n_321), .B (n_243), .C (n_338), .D (n_334), .Y
       (RegWe));
  nand4 g7919(.A (n_363), .B (n_362), .C (n_341), .D (n_320), .Y
       (Rs1Sel[1]));
  nand3 g7913(.A (n_308), .B (n_352), .C (n_315), .Y (n_361));
  nand3 g7914(.A (n_309), .B (n_353), .C (n_310), .Y (n_360));
  scandtype \state_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_344), .Q (\state[0] ), .nQ (n_39));
  nand4 g7917(.A (n_31), .B (n_33), .C (n_331), .D (n_323), .Y (n_359));
  nand3 g7936(.A (n_255), .B (n_330), .C (n_207), .Y (Op2Sel[0]));
  nand2 g7921(.A (n_340), .B (n_222), .Y (PcWe));
  nand3 g7939(.A (n_227), .B (n_336), .C (n_348), .Y (PcEn));
  inv g7955(.A (n_354), .Y (n_355));
  scandtype InISR_reg(.nReset (nReset), .Clock (Clock), .D (n_335), .Q
       (InISR), .nQ (n_476));
  nand4 g7956(.A (n_269), .B (n_302), .C (n_327), .D (n_181), .Y
       (n_354));
  nand2 g7945(.A (n_351), .B (Flags[0]), .Y (n_353));
  scandtype \stateSub_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_304), .Q (\stateSub[2] ), .nQ (n_177));
  nand2 g7946(.A (n_351), .B (Flags[1]), .Y (n_352));
  nand4 g7930(.A (n_277), .B (n_256), .C (n_287), .D (n_291), .Y
       (ImmSel));
  nand3 g7941(.A (n_300), .B (n_288), .C (n_348), .Y (nOE));
  nand2 g7947(.A (n_351), .B (Flags[2]), .Y (n_347));
  nand4 g7922(.A (n_317), .B (n_52), .C (n_303), .D (n_13), .Y
       (Rs1Sel[0]));
  nand2 g7948(.A (n_351), .B (Flags[3]), .Y (n_345));
  nand4 g7918(.A (n_68), .B (n_99), .C (n_290), .D (n_32), .Y (n_344));
  nor2 g7957(.A (n_329), .B (Op1Sel), .Y (n_343));
  and2 g7965(.A (n_326), .B (n_230), .Y (n_341));
  nor2 g7929(.A (n_314), .B (PcSel[2]), .Y (n_340));
  nor2 g7935(.A (n_316), .B (WdSel), .Y (n_338));
  inv g7980(.A (n_351), .Y (n_336));
  nand2 g7944(.A (n_285), .B (n_334), .Y (n_335));
  nand3 g7952(.A (n_239), .B (n_279), .C (n_185), .Y (MemEn));
  nand3 g7977(.A (n_218), .B (n_324), .C (n_50), .Y (nWE));
  nand2 g7949(.A (n_283), .B (\stateSub[1] ), .Y (n_331));
  nand2 g7966(.A (n_289), .B (n_249), .Y (n_330));
  nand3 g7979(.A (n_233), .B (n_251), .C (n_328), .Y (n_329));
  nand4 g7981(.A (n_205), .B (n_236), .C (n_246), .D (n_173), .Y
       (n_351));
  nor2 g7991(.A (n_272), .B (n_258), .Y (n_327));
  nand2 g7992(.A (n_286), .B (OpcodeCondIn[3]), .Y (n_326));
  nor2 g7962(.A (n_324), .B (n_323), .Y (ENB));
  nand3 g7964(.A (n_321), .B (n_280), .C (n_320), .Y (AluOR[1]));
  nand3 g7958(.A (n_284), .B (n_478), .C (n_293), .Y (PcSel[1]));
  nand4 g7924(.A (n_317), .B (n_122), .C (n_254), .D (n_7), .Y
       (RwSel[0]));
  nand4 g7951(.A (n_265), .B (n_223), .C (n_257), .D (n_170), .Y
       (n_316));
  nand2 g7926(.A (SysBus[1]), .B (n_312), .Y (n_315));
  nand4 g7959(.A (n_171), .B (n_221), .C (n_259), .D (n_74), .Y
       (n_314));
  nand2 g7927(.A (SysBus[2]), .B (n_312), .Y (n_313));
  nand2 g7928(.A (SysBus[3]), .B (n_312), .Y (n_311));
  nand2 g7925(.A (SysBus[0]), .B (n_312), .Y (n_310));
  nand2 g7931(.A (n_307), .B (\StatusReg[0] ), .Y (n_309));
  nand2 g7932(.A (n_307), .B (CFlag), .Y (n_308));
  nand2 g7933(.A (n_307), .B (\StatusReg[2] ), .Y (n_306));
  nand2 g7934(.A (n_307), .B (\StatusReg[3] ), .Y (n_305));
  nand3 g7978(.A (n_77), .B (n_117), .C (n_282), .Y (n_304));
  nor2 g7942(.A (n_224), .B (n_247), .Y (n_303));
  nand3 g7990(.A (\stateSub[1] ), .B (n_274), .C (n_273), .Y (n_302));
  scandtype IntReq_reg(.nReset (nReset), .Clock (Clock), .D (n_262), .Q
       (IntReq), .nQ ());
  nand3 g8002(.A (n_134), .B (n_300), .C (n_62), .Y (ALE));
  nand4 g7954(.A (n_363), .B (n_232), .C (n_298), .D (n_334), .Y
       (AluWe));
  nand2 g7971(.A (n_478), .B (n_235), .Y (LrEn));
  nand2 g7993(.A (n_270), .B (n_167), .Y (LrWe));
  nand2 g7969(.A (n_260), .B (n_293), .Y (PcSel[0]));
  nand4 g7943(.A (n_321), .B (n_199), .C (n_291), .D (n_334), .Y
       (RwSel[1]));
  nand2 g7950(.A (n_252), .B (\state[0] ), .Y (n_290));
  nand3 g8001(.A (n_203), .B (n_241), .C (n_196), .Y (n_289));
  inv g8007(.A (n_276), .Y (n_288));
  nand2 g7963(.A (n_266), .B (n_169), .Y (WdSel));
  inv g8018(.A (n_286), .Y (n_287));
  nand2 g7967(.A (InISR), .B (n_284), .Y (n_285));
  nand2 g7968(.A (n_282), .B (n_317), .Y (n_283));
  nand2 g7985(.A (n_280), .B (n_320), .Y (AluOR[0]));
  nand4 g7940(.A (n_180), .B (n_192), .C (n_212), .D (n_112), .Y
       (n_307));
  nor2 g7984(.A (n_278), .B (n_238), .Y (n_324));
  nand2 g7988(.A (n_278), .B (n_40), .Y (n_279));
  scandtype \state_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_229), .Q (\state[1] ), .nQ (n_193));
  and2 g7999(.A (n_225), .B (n_187), .Y (n_277));
  nand4 g8008(.A (n_111), .B (n_242), .C (n_156), .D (n_176), .Y
       (n_276));
  nand2 g7960(.A (n_244), .B (n_148), .Y (n_362));
  nand2 g8019(.A (n_298), .B (n_215), .Y (n_286));
  nand2 g8022(.A (n_274), .B (n_273), .Y (n_275));
  nor2 g8026(.A (n_298), .B (n_54), .Y (n_272));
  inv g8035(.A (n_270), .Y (LrSel));
  nand3 g8046(.A (n_248), .B (n_267), .C (n_268), .Y (n_280));
  nand4 g8058(.A (n_268), .B (n_100), .C (n_267), .D (OpcodeCondIn[2]),
       .Y (n_269));
  nand3 g7987(.A (n_264), .B (n_263), .C (n_175), .Y (n_266));
  nand2 g7989(.A (n_261), .B (n_220), .Y (n_284));
  nand3 g7994(.A (n_264), .B (n_263), .C (nWait), .Y (n_265));
  nand3 g7997(.A (n_213), .B (n_97), .C (n_107), .Y (n_262));
  and2 g7998(.A (n_261), .B (OpcodeCondIn[2]), .Y (n_312));
  nand2 g8000(.A (n_209), .B (n_253), .Y (n_260));
  nand3 g8003(.A (\state[0] ), .B (\stateSub[2] ), .C (n_200), .Y
       (n_282));
  nand3 g8006(.A (OpcodeCondIn[7]), .B (n_226), .C (OpcodeCondIn[3]),
       .Y (n_259));
  nor2 g8017(.A (n_216), .B (\stateSub[1] ), .Y (n_258));
  nor2 g8021(.A (n_219), .B (n_211), .Y (n_257));
  nand2 g8023(.A (n_250), .B (n_182), .Y (n_256));
  nand3 g8027(.A (n_245), .B (n_240), .C (OpcodeCondIn[4]), .Y (n_255));
  inv g7972(.A (n_228), .Y (n_254));
  and2 g8030(.A (n_253), .B (n_128), .Y (Op1Sel));
  nand3 g7974(.A (n_90), .B (n_189), .C (n_197), .Y (n_252));
  nand2 g8032(.A (n_250), .B (n_249), .Y (n_251));
  nand2 g8036(.A (n_253), .B (n_248), .Y (n_270));
  nand4 g7976(.A (n_143), .B (n_78), .C (n_188), .D (n_135), .Y
       (n_247));
  nand2 g8037(.A (n_250), .B (OpcodeCondIn[6]), .Y (n_246));
  nand2 g8042(.A (n_263), .B (n_245), .Y (n_291));
  nand3 g8044(.A (n_214), .B (n_217), .C (n_193), .Y (n_300));
  nand2 g7982(.A (n_195), .B (n_164), .Y (n_244));
  nand2 g8055(.A (n_267), .B (n_89), .Y (n_298));
  inv g8056(.A (n_250), .Y (n_243));
  trisbuf g453(.A (CFlag), .Enable (n_237), .Y (SysBus[1]));
  inv g8069(.A (n_242), .Y (n_274));
  nand2 g8072(.A (n_240), .B (OpcodeCondIn[4]), .Y (n_241));
  nand2 g7995(.A (n_238), .B (\stateSub[1] ), .Y (n_239));
  trisbuf g1(.A (\StatusReg[3] ), .Enable (n_237), .Y (SysBus[3]));
  trisbuf g452(.A (\StatusReg[2] ), .Enable (n_237), .Y (SysBus[2]));
  nand2 g8085(.A (n_240), .B (n_234), .Y (n_236));
  trisbuf g454(.A (\StatusReg[0] ), .Enable (n_237), .Y (SysBus[0]));
  nand4 g8005(.A (n_234), .B (\stateSub[1] ), .C (n_231), .D
       (OpcodeCondIn[2]), .Y (n_235));
  nor2 g8012(.A (n_208), .B (\state[1] ), .Y (n_278));
  nand2 g8020(.A (n_210), .B (n_163), .Y (n_233));
  nand3 g8024(.A (n_91), .B (n_231), .C (\stateSub[0] ), .Y (n_232));
  nand3 g8025(.A (\stateSub[0] ), .B (n_231), .C (n_245), .Y (n_230));
  nand2 g7970(.A (n_198), .B (n_146), .Y (n_229));
  nand3 g7973(.A (n_158), .B (n_174), .C (n_41), .Y (n_228));
  nand2 g8029(.A (n_226), .B (n_268), .Y (n_227));
  nand2 g8031(.A (n_240), .B (n_157), .Y (n_225));
  nand3 g7975(.A (n_479), .B (n_178), .C (n_183), .Y (n_224));
  nand3 g8047(.A (n_248), .B (n_202), .C (n_234), .Y (n_223));
  nor2 g8057(.A (n_222), .B (OpcodeCondIn[4]), .Y (n_250));
  nand3 g7986(.A (n_161), .B (n_194), .C (n_220), .Y (n_221));
  nor2 g8059(.A (n_222), .B (n_18), .Y (n_219));
  nand2 g8063(.A (n_217), .B (n_184), .Y (n_218));
  nand2 g8068(.A (n_231), .B (\stateSub[0] ), .Y (n_216));
  nand2 g8070(.A (n_231), .B (OpcodeCondIn[6]), .Y (n_242));
  nand2 g8071(.A (n_231), .B (n_214), .Y (n_215));
  nor2 g8073(.A (n_222), .B (n_64), .Y (n_253));
  scandtype \stateSub_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_186), .Q (\stateSub[0] ), .nQ (n_29));
  nand2 g8081(.A (IntReq), .B (n_293), .Y (n_213));
  inv g8013(.A (n_321), .Y (n_261));
  and2 g8041(.A (n_179), .B (n_130), .Y (n_212));
  and2 g8076(.A (n_206), .B (n_60), .Y (n_211));
  nand2 g8075(.A (n_201), .B (n_149), .Y (n_210));
  nand4 g8051(.A (n_94), .B (n_48), .C (n_141), .D (n_23), .Y (n_209));
  nor2 g8064(.A (n_154), .B (n_76), .Y (n_208));
  nand2 g8074(.A (n_206), .B (n_83), .Y (n_207));
  nand2 g8077(.A (n_206), .B (n_92), .Y (n_205));
  nand4 g7953(.A (n_24), .B (n_72), .C (n_144), .D (n_119), .Y (nME));
  nand2 g8083(.A (n_206), .B (OpcodeCondIn[3]), .Y (n_203));
  and2 g8084(.A (n_202), .B (n_129), .Y (n_226));
  nor2 g8086(.A (n_201), .B (n_323), .Y (n_263));
  nand2 g8088(.A (n_147), .B (n_61), .Y (n_200));
  nand3 g8089(.A (n_124), .B (n_191), .C (n_190), .Y (n_199));
  nand4 g8004(.A (n_197), .B (n_137), .C (IntReq), .D (\state[0] ), .Y
       (n_198));
  inv g8113(.A (n_222), .Y (n_240));
  inv g8115(.A (n_196), .Y (n_267));
  nand2 g8009(.A (n_194), .B (n_29), .Y (n_195));
  and2 g8010(.A (n_194), .B (n_193), .Y (n_238));
  nand2 g8014(.A (n_194), .B (n_192), .Y (n_321));
  nand3 g8033(.A (n_151), .B (n_191), .C (n_190), .Y (n_363));
  nand2 g8034(.A (n_136), .B (n_160), .Y (n_189));
  nand2 g8038(.A (n_166), .B (OpcodeCondIn[6]), .Y (n_188));
  and2 g8039(.A (n_162), .B (n_248), .Y (n_237));
  nand2 g8040(.A (n_202), .B (n_159), .Y (n_187));
  nand3 g8043(.A (n_57), .B (n_127), .C (n_42), .Y (n_186));
  nand3 g8045(.A (n_184), .B (n_165), .C (\stateSub[0] ), .Y (n_185));
  nand3 g8048(.A (n_150), .B (\stateSub[2] ), .C (n_182), .Y (n_183));
  nand3 g8050(.A (n_140), .B (n_192), .C (n_172), .Y (n_181));
  nand2 g8061(.A (\stateSub[2] ), .B (n_142), .Y (n_180));
  nand2 g8062(.A (n_177), .B (n_133), .Y (n_179));
  nand2 g8066(.A (n_138), .B (n_177), .Y (n_178));
  nand3 g8079(.A (n_184), .B (n_168), .C (n_175), .Y (n_176));
  nand2 g7996(.A (n_131), .B (\state[0] ), .Y (n_174));
  inv g8101(.A (n_153), .Y (n_217));
  inv g8105(.A (PcSel[2]), .Y (n_293));
  nand2 g8109(.A (n_191), .B (n_96), .Y (n_173));
  inv g8111(.A (n_201), .Y (n_231));
  nand2 g8114(.A (n_191), .B (OpcodeCondIn[5]), .Y (n_222));
  nand2 g8116(.A (n_191), .B (n_172), .Y (n_196));
  nand2 g8117(.A (n_191), .B (n_109), .Y (n_171));
  nand2 g8120(.A (n_191), .B (n_249), .Y (n_170));
  nand4 g8011(.A (n_245), .B (n_168), .C (n_192), .D (n_220), .Y
       (n_169));
  nand4 g8015(.A (n_245), .B (n_168), .C (n_192), .D (OpcodeCondIn[2]),
       .Y (n_167));
  nand2 g8078(.A (n_123), .B (n_323), .Y (n_166));
  and2 g8052(.A (n_165), .B (n_132), .Y (n_194));
  nand2 g8053(.A (n_165), .B (n_163), .Y (n_164));
  and2 g8054(.A (n_161), .B (n_165), .Y (n_162));
  nand2 g8065(.A (n_126), .B (n_88), .Y (n_160));
  nand2 g8067(.A (n_101), .B (n_139), .Y (n_159));
  nand2 g8080(.A (n_125), .B (\stateSub[2] ), .Y (n_158));
  nand3 g8087(.A (n_82), .B (n_95), .C (n_53), .Y (n_157));
  nand3 g8090(.A (n_152), .B (n_161), .C (n_248), .Y (n_156));
  nor2 g8092(.A (n_155), .B (OpcodeCondIn[5]), .Y (n_206));
  nor2 g8095(.A (n_155), .B (OpcodeCondIn[4]), .Y (n_202));
  and2 g8100(.A (n_168), .B (n_264), .Y (n_154));
  nor2 g8102(.A (n_168), .B (n_152), .Y (n_153));
  inv g8103(.A (n_150), .Y (n_151));
  nor2 g8106(.A (n_145), .B (n_193), .Y (PcSel[2]));
  nand2 g8110(.A (n_152), .B (n_148), .Y (n_149));
  nand2 g8112(.A (n_168), .B (n_148), .Y (n_201));
  and2 g8123(.A (n_106), .B (n_49), .Y (n_348));
  nand2 g8126(.A (n_115), .B (OpcodeCondIn[4]), .Y (n_147));
  nand2 g8129(.A (n_145), .B (\state[1] ), .Y (n_146));
  nand4 g8049(.A (n_66), .B (\state[0] ), .C (\stateSub[1] ), .D
       (OpcodeCondIn[7]), .Y (n_144));
  nand3 g8060(.A (\state[0] ), .B (n_177), .C (n_118), .Y (n_143));
  nand2 g8093(.A (n_114), .B (n_67), .Y (n_142));
  nor2 g8094(.A (n_85), .B (n_58), .Y (n_141));
  inv g8097(.A (n_139), .Y (n_140));
  nand2 g8099(.A (n_104), .B (n_86), .Y (n_138));
  nand2 g8104(.A (n_84), .B (n_80), .Y (n_150));
  nand2 g8107(.A (n_136), .B (n_108), .Y (n_137));
  nand2 g8122(.A (\stateSub[2] ), .B (n_87), .Y (n_135));
  nand2 g8127(.A (n_113), .B (\stateSub[0] ), .Y (n_134));
  nand3 g8130(.A (n_132), .B (n_190), .C (OpcodeCondIn[2]), .Y (n_133));
  nand4 g8016(.A (n_172), .B (\stateSub[1] ), .C (n_65), .D
       (OpcodeCondIn[3]), .Y (n_131));
  nand2 g8082(.A (n_98), .B (OpcodeCondIn[5]), .Y (n_130));
  inv g8151(.A (n_128), .Y (n_129));
  inv g8160(.A (n_155), .Y (n_191));
  nand2 g8091(.A (n_73), .B (\stateSub[0] ), .Y (n_127));
  nand2 g8096(.A (n_71), .B (n_268), .Y (n_126));
  nand3 g8098(.A (n_220), .B (n_268), .C (n_132), .Y (n_139));
  nand2 g8108(.A (n_120), .B (n_124), .Y (n_125));
  nand2 g8118(.A (n_121), .B (\stateSub[1] ), .Y (n_123));
  nand2 g8119(.A (n_121), .B (n_120), .Y (n_122));
  nand2 g8121(.A (\state[0] ), .B (n_118), .Y (n_119));
  inv g8124(.A (n_102), .Y (n_165));
  nand2 g8128(.A (n_69), .B (\stateSub[2] ), .Y (n_117));
  inv g8137(.A (n_114), .Y (n_115));
  inv g8141(.A (n_113), .Y (n_320));
  and2 g8143(.A (n_177), .B (n_190), .Y (n_152));
  nor2 g8145(.A (\stateSub[2] ), .B (n_112), .Y (n_168));
  nand2 g8148(.A (n_110), .B (n_214), .Y (n_334));
  nand2 g8150(.A (n_110), .B (\stateSub[0] ), .Y (n_111));
  nand2 g8152(.A (n_81), .B (n_220), .Y (n_128));
  inv g8153(.A (n_108), .Y (n_109));
  nand2 g8161(.A (n_192), .B (\stateSub[2] ), .Y (n_155));
  nand2 g8164(.A (n_110), .B (n_51), .Y (n_328));
  nand2 g8168(.A (IRQ1), .B (n_473), .Y (n_107));
  nand2 g8171(.A (n_105), .B (\state[1] ), .Y (n_106));
  nand2 g8177(.A (n_105), .B (\stateSub[2] ), .Y (n_145));
  nand2 g8144(.A (n_56), .B (n_175), .Y (n_104));
  nor2 g8159(.A (n_34), .B (n_323), .Y (IrWe));
  nand3 g8125(.A (n_268), .B (n_177), .C (n_172), .Y (n_102));
  nand3 g8132(.A (n_268), .B (n_100), .C (OpcodeCondIn[2]), .Y (n_101));
  nand4 g8133(.A (n_172), .B (\stateSub[2] ), .C (n_120), .D (n_175),
       .Y (n_99));
  mux2 g8134(.S (OpcodeCondIn[4]), .I0 (n_249), .I1 (n_63), .Y (n_98));
  nand2 g8136(.A (n_476), .B (IRQ2), .Y (n_97));
  nand2 g8138(.A (n_268), .B (n_19), .Y (n_114));
  nand2 g8140(.A (n_37), .B (n_15), .Y (n_96));
  nor2 g8142(.A (n_75), .B (\stateSub[1] ), .Y (n_113));
  nand3 g8147(.A (n_220), .B (n_93), .C (n_182), .Y (n_95));
  nand3 g8149(.A (n_45), .B (n_46), .C (n_93), .Y (n_94));
  nor2 g8154(.A (n_92), .B (n_14), .Y (n_108));
  nand2 g8155(.A (n_55), .B (n_43), .Y (n_91));
  nand3 g8157(.A (n_89), .B (\stateSub[2] ), .C (n_172), .Y (n_90));
  nand2 g8158(.A (n_268), .B (n_132), .Y (n_88));
  nand2 g8167(.A (n_38), .B (n_6), .Y (n_87));
  nand3 g8169(.A (n_264), .B (n_197), .C (OpcodeCondIn[2]), .Y (n_86));
  and2 g8172(.A (n_47), .B (n_132), .Y (n_85));
  xor2 g8180(.A (n_79), .B (OpcodeCondIn[2]), .Y (n_84));
  inv g8187(.A (n_82), .Y (n_83));
  and2 g8195(.A (n_197), .B (n_39), .Y (n_105));
  nand2 g8204(.A (n_80), .B (n_79), .Y (n_81));
  nand2 g8207(.A (n_136), .B (n_249), .Y (n_78));
  and2 g8209(.A (n_234), .B (n_172), .Y (n_190));
  nand2 g8211(.A (n_76), .B (n_197), .Y (n_77));
  inv g8217(.A (n_75), .Y (n_110));
  and2 g8214(.A (n_148), .B (n_197), .Y (n_192));
  nand3 g8178(.A (n_12), .B (n_148), .C (n_177), .Y (n_74));
  nand2 g8192(.A (n_89), .B (n_172), .Y (n_112));
  nand2 g8135(.A (n_72), .B (n_17), .Y (n_73));
  nand2 g8139(.A (n_70), .B (n_20), .Y (n_71));
  and2 g8146(.A (n_177), .B (n_25), .Y (n_121));
  nand2 g8156(.A (n_70), .B (OpcodeCondIn[7]), .Y (n_124));
  nand2 g8162(.A (n_317), .B (n_197), .Y (n_69));
  nand3 g8163(.A (n_197), .B (n_76), .C (n_193), .Y (n_68));
  nand2 g8222(.A (n_172), .B (OpcodeCondIn[6]), .Y (n_67));
  nand2 g8166(.A (n_28), .B (n_172), .Y (n_118));
  nand3 g8170(.A (n_79), .B (n_80), .C (n_8), .Y (n_66));
  and2 g8173(.A (n_30), .B (n_44), .Y (n_65));
  nand2 g8174(.A (n_63), .B (OpcodeCondIn[4]), .Y (n_64));
  nand3 g8175(.A (n_214), .B (n_76), .C (n_193), .Y (n_62));
  nand2 g8176(.A (n_63), .B (n_172), .Y (n_61));
  mux2 g8179(.S (n_234), .I0 (OpcodeCondIn[4]), .I1 (n_89), .Y (n_60));
  and2 g8184(.A (n_79), .B (n_220), .Y (n_58));
  nand2 g8188(.A (n_27), .B (n_89), .Y (n_82));
  nand2 g8199(.A (n_76), .B (n_163), .Y (n_57));
  nand2 g8200(.A (n_16), .B (n_163), .Y (n_56));
  nand2 g8202(.A (n_163), .B (n_54), .Y (n_55));
  and2 g8205(.A (n_148), .B (\stateSub[1] ), .Y (n_161));
  nand2 g8210(.A (n_234), .B (OpcodeCondIn[4]), .Y (n_53));
  nand2 g8213(.A (n_51), .B (\stateSub[2] ), .Y (n_52));
  nand2 g8215(.A (n_76), .B (\stateSub[0] ), .Y (n_50));
  nand2 g8218(.A (n_76), .B (\state[1] ), .Y (n_75));
  nand2 g8223(.A (n_76), .B (n_184), .Y (n_49));
  nand3 g8165(.A (n_100), .B (n_477), .C (OpcodeCondIn[2]), .Y (n_48));
  nand2 g8227(.A (n_46), .B (n_45), .Y (n_47));
  nand2 g8216(.A (n_44), .B (n_26), .Y (n_92));
  nand2 g8197(.A (n_220), .B (n_234), .Y (n_43));
  nand2 g8193(.A (n_184), .B (n_177), .Y (n_42));
  nand2 g8185(.A (n_40), .B (n_39), .Y (n_41));
  and2 g8208(.A (n_234), .B (OpcodeCondIn[7]), .Y (n_268));
  nand2 g8206(.A (n_44), .B (n_9), .Y (n_38));
  scandtype IRQ2_reg(.nReset (nReset), .Clock (Clock), .D (IRQ1), .Q
       (IRQ2), .nQ (n_473));
  nand2 g8183(.A (n_21), .B (n_89), .Y (n_37));
  inv g8190(.A (n_70), .Y (n_248));
  nand2 g8196(.A (n_76), .B (n_193), .Y (n_34));
  nand2 g8198(.A (n_76), .B (n_40), .Y (n_33));
  and2 g8201(.A (n_32), .B (n_177), .Y (n_72));
  inv g8255(.A (n_51), .Y (n_197));
  nand3 g8212(.A (\stateSub[0] ), .B (n_177), .C (n_193), .Y (n_31));
  nand3 g8220(.A (n_264), .B (n_29), .C (OpcodeCondIn[2]), .Y (n_30));
  inv g8231(.A (n_100), .Y (n_79));
  inv g8236(.A (n_80), .Y (n_93));
  nand2 g8219(.A (n_11), .B (OpcodeCondIn[7]), .Y (n_28));
  inv g8246(.A (n_26), .Y (n_27));
  inv g8250(.A (n_54), .Y (n_245));
  inv g8253(.A (n_44), .Y (n_249));
  nand2 g8221(.A (n_132), .B (OpcodeCondIn[7]), .Y (n_25));
  nand2 g8191(.A (n_220), .B (n_22), .Y (n_70));
  mux2 g8225(.S (n_193), .I0 (\stateSub[1] ), .I1 (\stateSub[0] ), .Y
       (n_24));
  xor2 g8224(.A (n_193), .B (n_39), .Y (n_317));
  nand2 g8203(.A (\StatusReg[0] ), .B (n_22), .Y (n_23));
  inv g8241(.A (n_40), .Y (n_214));
  and2 g8186(.A (n_175), .B (n_182), .Y (n_63));
  inv g8233(.A (n_21), .Y (n_172));
  nand2 g8254(.A (n_264), .B (OpcodeCondIn[7]), .Y (n_44));
  nand2 g8234(.A (n_20), .B (n_19), .Y (n_21));
  xor2 g8226(.A (OpcodeCondIn[7]), .B (OpcodeCondIn[3]), .Y (n_18));
  scandtype IRQ1_reg(.nReset (nReset), .Clock (Clock), .D (n_5), .Q
       (IRQ1), .nQ ());
  nand2 g8229(.A (n_193), .B (n_3), .Y (n_17));
  nor2 g8232(.A (n_10), .B (OpcodeCondIn[0]), .Y (n_100));
  nand2 g8235(.A (\StatusReg[3] ), .B (n_474), .Y (n_45));
  and2 g8243(.A (n_193), .B (n_163), .Y (n_184));
  and2 g8244(.A (n_177), .B (n_39), .Y (n_76));
  nand2 g8245(.A (\state[0] ), .B (n_29), .Y (n_16));
  nand2 g8247(.A (n_175), .B (OpcodeCondIn[4]), .Y (n_26));
  and2 g8248(.A (\state[0] ), .B (n_193), .Y (n_148));
  nand2 g8249(.A (n_264), .B (OpcodeCondIn[4]), .Y (n_15));
  nor2 g8252(.A (n_20), .B (OpcodeCondIn[7]), .Y (n_14));
  nand2 g8257(.A (\stateSub[1] ), .B (n_39), .Y (n_13));
  nand2 g8256(.A (\stateSub[1] ), .B (n_29), .Y (n_51));
  inv g8265(.A (n_323), .Y (n_12));
  nor2 g8269(.A (n_39), .B (n_264), .Y (n_120));
  nand2 g8242(.A (n_163), .B (n_29), .Y (n_40));
  nand2 g8238(.A (\StatusReg[2] ), .B (n_475), .Y (n_46));
  inv g8260(.A (n_11), .Y (n_234));
  nor2 g8240(.A (n_177), .B (OpcodeCondIn[5]), .Y (n_136));
  nand2 g8237(.A (n_10), .B (OpcodeCondIn[0]), .Y (n_80));
  nand2 g8251(.A (n_264), .B (OpcodeCondIn[3]), .Y (n_54));
  nand2 g8239(.A (n_19), .B (OpcodeCondIn[3]), .Y (n_9));
  nand2 g8259(.A (OpcodeCondIn[2]), .B (OpcodeCondIn[1]), .Y (n_8));
  nand2 g8266(.A (\stateSub[1] ), .B (\stateSub[0] ), .Y (n_323));
  and2 g8267(.A (OpcodeCondIn[7]), .B (OpcodeCondIn[6]), .Y (n_182));
  nand2 g8268(.A (\stateSub[0] ), .B (OpcodeCondIn[6]), .Y (n_7));
  nand2 g8264(.A (OpcodeCondIn[3]), .B (OpcodeCondIn[2]), .Y (n_273));
  nand2 g8263(.A (OpcodeCondIn[7]), .B (OpcodeCondIn[4]), .Y (n_6));
  nand2 g8262(.A (\state[1] ), .B (\state[0] ), .Y (n_32));
  nand2 g8261(.A (OpcodeCondIn[6]), .B (OpcodeCondIn[3]), .Y (n_11));
  nor2 g8230(.A (OpcodeCondIn[0]), .B (OpcodeCondIn[1]), .Y (n_132));
  and2 g8258(.A (OpcodeCondIn[0]), .B (OpcodeCondIn[1]), .Y (n_22));
  inv g8271(.A (nIRQ), .Y (n_5));
  inv g8285(.A (OpcodeCondIn[7]), .Y (n_89));
  inv g8276(.A (nWait), .Y (n_3));
  inv g8270(.A (OpcodeCondIn[3]), .Y (n_175));
  inv g8280(.A (OpcodeCondIn[2]), .Y (n_220));
  inv g8282(.A (OpcodeCondIn[6]), .Y (n_264));
  inv g8274(.A (OpcodeCondIn[5]), .Y (n_19));
  inv g8278(.A (OpcodeCondIn[4]), .Y (n_20));
  inv g8286(.A (OpcodeCondIn[1]), .Y (n_10));
  nand3 g2(.A (n_253), .B (n_100), .C (n_220), .Y (n_478));
  nand4 g8343(.A (\stateSub[0] ), .B (\state[0] ), .C (n_89), .D
       (n_234), .Y (n_479));
endmodule

