
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

  timeunit 1ns;
  timeprecision 10ps;
module control(ALE, AluEn, AluWe, AluOR, CFlag, ENB, ImmSel, IrWe,
     LrEn, LrSel, LrWe, MemEn, nME, nOE, nWE, Op1Sel, Op2Sel, PcEn,
     PcSel, PcWe, RegWe, Rs1Sel, RwSel, WdSel, SysBus, Clock, Flags,
     nIRQ, nReset, nWait, OpcodeCondIn);
  input Clock, nIRQ, nReset, nWait;
  input [3:0] Flags;
  input [7:0] OpcodeCondIn;
  output ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel,
       LrWe, MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel;
  output [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  output [2:0] PcSel;
  inout [15:0] SysBus;
  wire Clock, nIRQ, nReset, nWait;
  wire [3:0] Flags;
  wire [7:0] OpcodeCondIn;
  wire ALE, AluEn, AluWe, CFlag, ENB, ImmSel, IrWe, LrEn, LrSel, LrWe,
       MemEn, nME, nOE, nWE, Op1Sel, PcEn, PcWe, RegWe, WdSel;
  wire [1:0] AluOR, Op2Sel, Rs1Sel, RwSel;
  wire [2:0] PcSel;
  wire [15:0] SysBus;
  wire IRQ1, IRQ2, IntReq, \StatusReg[0] , \StatusReg[2] ,
       \StatusReg[3] , n_0, n_3;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_282;
  wire n_283, n_285, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_300, n_301, n_302, n_303, n_304, n_305, n_308, n_309;
  wire n_311, n_312, n_313, n_314, n_315, n_316, n_317, n_318;
  wire n_319, n_320, n_321, n_322, n_323, n_324, n_325, n_326;
  wire n_327, n_328, n_330, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_350, n_351, n_352, n_353, n_354;
  wire n_355, n_356, n_357, n_358, n_361, n_362, n_363, n_364;
  wire n_365, n_366, n_367, n_368, n_369, n_373, n_374, n_375;
  wire n_376, n_377, n_378, n_379, n_380, n_381, n_382, n_386;
  wire n_387, n_388, n_391, n_392, n_394, n_395, n_396, n_397;
  wire n_398, n_399, n_401, n_403, n_404, n_405, n_406, n_409;
  wire n_412, n_484, n_485, n_486, n_487, n_488, \stateSub[0] ,
       \stateSub[1] ;
  wire \stateSub[2] , \state[0] , \state[1] ;
  nand4 g16040(.A (n_260), .B (n_221), .C (n_403), .D (n_409), .Y
       (Op2Sel[1]));
  nand3 g16029(.A (n_409), .B (n_406), .C (n_404), .Y (RegWe));
  scandtype \StatusReg_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_399), .Q (\StatusReg[0] ), .nQ (n_485));
  scandtype \StatusReg_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_398), .Q (CFlag), .nQ ());
  scandtype InISR_reg(.nReset (nReset), .Clock (Clock), .D (n_405), .Q
       (n_412), .nQ (n_488));
  scandtype \StatusReg_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_397), .Q (\StatusReg[2] ), .nQ (n_487));
  scandtype \StatusReg_reg[3] (.nReset (nReset), .Clock (Clock), .D
       (n_396), .Q (\StatusReg[3] ), .nQ (n_486));
  nand4 g16028(.A (n_346), .B (n_250), .C (n_394), .D (n_347), .Y
       (Rs1Sel[0]));
  nand4 g16038(.A (n_200), .B (n_330), .C (n_386), .D (n_401), .Y
       (nOE));
  nor2 g16036(.A (n_391), .B (n_257), .Y (n_406));
  nand2 g16060(.A (n_387), .B (n_404), .Y (n_405));
  inv g16066(.A (n_395), .Y (n_403));
  nand3 g16034(.A (n_401), .B (n_379), .C (n_127), .Y (PcEn));
  nand2 g16049(.A (n_392), .B (n_409), .Y (Rs1Sel[1]));
  nand3 g16041(.A (n_339), .B (n_378), .C (n_355), .Y (n_399));
  nand3 g16042(.A (n_338), .B (n_377), .C (n_354), .Y (n_398));
  nand3 g16043(.A (n_336), .B (n_375), .C (n_351), .Y (n_397));
  nand3 g16044(.A (n_335), .B (n_374), .C (n_350), .Y (n_396));
  nand4 g16067(.A (n_367), .B (n_267), .C (n_265), .D (n_129), .Y
       (n_395));
  nor2 g16039(.A (n_380), .B (n_82), .Y (n_394));
  scandtype \stateSub_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_382), .Q (\stateSub[0] ), .nQ (n_286));
  nand4 g16063(.A (n_373), .B (n_289), .C (n_287), .D (n_404), .Y
       (AluWe));
  nor2 g16057(.A (n_369), .B (n_296), .Y (n_392));
  nand4 g16045(.A (n_232), .B (n_205), .C (n_358), .D (n_153), .Y
       (n_391));
  nand3 g16102(.A (n_293), .B (n_388), .C (n_101), .Y (MemEn));
  nand3 g16078(.A (n_327), .B (n_388), .C (n_364), .Y (nWE));
  nand2 g16075(.A (n_412), .B (n_366), .Y (n_387));
  inv g16079(.A (n_381), .Y (n_386));
  nand4 g16072(.A (n_252), .B (n_283), .C (n_344), .D (n_368), .Y
       (AluEn));
  nand2 g16094(.A (n_362), .B (n_84), .Y (ENB));
  nand3 g16085(.A (n_363), .B (n_328), .C (n_401), .Y (PcSel[1]));
  nand4 g16048(.A (n_116), .B (n_124), .C (n_341), .D (n_115), .Y
       (n_382));
  nand3 g16080(.A (n_179), .B (n_352), .C (n_131), .Y (n_381));
  nand4 g16050(.A (n_51), .B (n_212), .C (n_342), .D (n_29), .Y
       (n_380));
  nand2 g16051(.A (n_365), .B (n_261), .Y (n_379));
  nand2 g16052(.A (SysBus[0]), .B (n_376), .Y (n_378));
  nand2 g16053(.A (SysBus[1]), .B (n_376), .Y (n_377));
  nand2 g16054(.A (SysBus[2]), .B (n_376), .Y (n_375));
  nand2 g16055(.A (SysBus[3]), .B (n_376), .Y (n_374));
  nand2 g16118(.A (n_333), .B (n_340), .Y (n_373));
  scandtype \state_reg[0] (.nReset (nReset), .Clock (Clock), .D
       (n_357), .Q (\state[0] ), .nQ (n_38));
  nand4 g16064(.A (n_295), .B (n_248), .C (n_316), .D (n_334), .Y
       (ImmSel));
  nand4 g16037(.A (n_345), .B (n_130), .C (n_332), .D (n_225), .Y
       (nME));
  nand3 g16065(.A (n_244), .B (n_318), .C (n_198), .Y (Op2Sel[0]));
  nand4 g16084(.A (n_298), .B (n_206), .C (n_259), .D (n_368), .Y
       (n_369));
  nand2 g16092(.A (n_317), .B (n_356), .Y (n_367));
  nand3 g16103(.A (\stateSub[2] ), .B (n_64), .C (n_322), .Y (n_366));
  nand2 g16059(.A (n_364), .B (n_325), .Y (n_365));
  nand2 g16110(.A (n_319), .B (n_305), .Y (n_363));
  scandtype \state_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_324), .Q (\state[1] ), .nQ (n_14));
  nand2 g16123(.A (n_152), .B (n_361), .Y (n_388));
  nand2 g16124(.A (n_172), .B (n_361), .Y (n_362));
  nand3 g16061(.A (n_154), .B (n_401), .C (n_302), .Y (PcWe));
  nand4 g16081(.A (n_409), .B (n_279), .C (n_254), .D (n_404), .Y
       (RwSel[1]));
  inv g16082(.A (n_343), .Y (n_358));
  nand3 g16058(.A (n_311), .B (n_282), .C (n_73), .Y (n_357));
  nand2 g16109(.A (n_321), .B (n_211), .Y (n_356));
  nand2 g16068(.A (n_353), .B (\StatusReg[0] ), .Y (n_355));
  nand2 g16069(.A (n_353), .B (CFlag), .Y (n_354));
  nand2 g16116(.A (n_300), .B (n_274), .Y (n_352));
  nand2 g16070(.A (n_353), .B (\StatusReg[2] ), .Y (n_351));
  nand2 g16071(.A (n_353), .B (\StatusReg[3] ), .Y (n_350));
  nand3 g16122(.A (n_409), .B (n_309), .C (n_308), .Y (AluOR[1]));
  nand4 g16062(.A (n_347), .B (n_346), .C (n_294), .D (n_345), .Y
       (RwSel[0]));
  inv g16131(.A (n_323), .Y (n_344));
  nand3 g16083(.A (n_219), .B (n_297), .C (n_209), .Y (n_343));
  inv g16086(.A (n_320), .Y (n_342));
  nand2 g16088(.A (n_315), .B (n_286), .Y (n_341));
  nand2 g16153(.A (n_314), .B (n_171), .Y (n_340));
  nand2 g16095(.A (n_337), .B (Flags[0]), .Y (n_339));
  nand2 g16096(.A (n_337), .B (Flags[1]), .Y (n_338));
  nand2 g16098(.A (n_337), .B (Flags[2]), .Y (n_336));
  nand2 g16099(.A (n_337), .B (Flags[3]), .Y (n_335));
  nand2 g16119(.A (n_333), .B (n_277), .Y (n_334));
  inv g16073(.A (n_312), .Y (n_332));
  nand2 g16117(.A (n_330), .B (n_132), .Y (ALE));
  nand2 g16101(.A (n_328), .B (n_246), .Y (LrEn));
  trisbuf g1(.A (\StatusReg[3] ), .Enable (n_326), .Y (SysBus[3]));
  nand2 g16127(.A (n_285), .B (n_269), .Y (n_327));
  trisbuf g469(.A (\StatusReg[2] ), .Enable (n_326), .Y (SysBus[2]));
  trisbuf g470(.A (CFlag), .Enable (n_326), .Y (SysBus[1]));
  trisbuf g471(.A (\StatusReg[0] ), .Enable (n_326), .Y (SysBus[0]));
  nand2 g16076(.A (n_292), .B (n_278), .Y (n_325));
  nand2 g16077(.A (n_299), .B (n_111), .Y (n_324));
  nand3 g16132(.A (n_236), .B (n_187), .C (n_270), .Y (n_323));
  inv g16134(.A (n_321), .Y (n_322));
  nand4 g16087(.A (n_112), .B (n_54), .C (n_262), .D (n_48), .Y
       (n_320));
  inv g16142(.A (n_304), .Y (n_361));
  inv g16154(.A (n_409), .Y (n_319));
  nand2 g16093(.A (n_288), .B (n_251), .Y (n_318));
  nand2 g16168(.A (n_317), .B (n_313), .Y (n_368));
  nor2 g16111(.A (n_258), .B (n_165), .Y (n_316));
  nand3 g16113(.A (n_273), .B (n_203), .C (n_52), .Y (n_315));
  inv g16200(.A (n_313), .Y (n_314));
  nand4 g16074(.A (n_46), .B (n_223), .C (n_311), .D (n_41), .Y
       (n_312));
  scandtype \stateSub_reg[2] (.nReset (nReset), .Clock (Clock), .D
       (n_247), .Q (\stateSub[2] ), .nQ (n_225));
  nand2 g16147(.A (n_309), .B (n_308), .Y (AluOR[0]));
  nand2 g16125(.A (n_280), .B (n_189), .Y (LrWe));
  nand2 g16100(.A (n_264), .B (n_401), .Y (PcSel[0]));
  nand2 g16128(.A (n_242), .B (n_255), .Y (n_337));
  nand2 g16135(.A (n_303), .B (n_305), .Y (n_321));
  nor2 g16143(.A (n_303), .B (n_192), .Y (n_304));
  nand2 g16089(.A (n_301), .B (n_271), .Y (n_302));
  nand4 g16090(.A (n_108), .B (n_301), .C (n_234), .D (n_230), .Y
       (n_353));
  nand2 g16155(.A (n_191), .B (n_303), .Y (n_409));
  nand2 g16165(.A (n_184), .B (n_268), .Y (n_300));
  nand3 g16104(.A (n_226), .B (IntReq), .C (\state[0] ), .Y (n_299));
  inv g16173(.A (n_275), .Y (n_326));
  nand3 g16192(.A (n_291), .B (n_266), .C (n_290), .Y (n_298));
  nand3 g16112(.A (n_253), .B (n_296), .C (nWait), .Y (n_297));
  nand3 g16114(.A (n_44), .B (n_263), .C (n_15), .Y (n_328));
  nand2 g16201(.A (n_224), .B (n_276), .Y (n_313));
  nand2 g16120(.A (n_243), .B (n_222), .Y (n_295));
  nor2 g16121(.A (n_214), .B (n_249), .Y (n_294));
  scandtype IntReq_reg(.nReset (nReset), .Clock (Clock), .D (n_217), .Q
       (IntReq), .nQ ());
  nand3 g16221(.A (n_292), .B (n_291), .C (n_290), .Y (n_293));
  nand4 g16126(.A (n_159), .B (\stateSub[1] ), .C (n_272), .D (n_305),
       .Y (n_289));
  nand3 g16130(.A (n_207), .B (n_196), .C (n_157), .Y (n_288));
  nand2 g16137(.A (n_241), .B (n_286), .Y (n_287));
  nand2 g16145(.A (n_235), .B (n_58), .Y (n_285));
  inv g16148(.A (n_283), .Y (Op1Sel));
  nand2 g16091(.A (n_231), .B (n_125), .Y (n_282));
  inv g16160(.A (n_280), .Y (LrSel));
  nand2 g16164(.A (n_237), .B (n_228), .Y (n_279));
  nand4 g16097(.A (n_49), .B (n_194), .C (n_183), .D (n_193), .Y
       (n_278));
  and2 g16166(.A (n_240), .B (n_83), .Y (n_330));
  nand2 g16171(.A (n_229), .B (n_276), .Y (n_277));
  nand3 g16174(.A (n_290), .B (n_245), .C (n_274), .Y (n_275));
  nand2 g16179(.A (n_272), .B (n_123), .Y (n_273));
  nand2 g16108(.A (n_186), .B (n_156), .Y (n_271));
  nand2 g16186(.A (n_272), .B (n_269), .Y (n_270));
  nand2 g16187(.A (n_272), .B (\stateSub[0] ), .Y (n_268));
  nand3 g16188(.A (n_291), .B (n_266), .C (n_238), .Y (n_267));
  and2 g16193(.A (n_290), .B (n_227), .Y (n_303));
  nand2 g16194(.A (n_239), .B (n_290), .Y (n_265));
  nand2 g16115(.A (n_216), .B (n_263), .Y (n_264));
  nand2 g16212(.A (n_218), .B (n_290), .Y (n_309));
  scandtype \stateSub_reg[1] (.nReset (nReset), .Clock (Clock), .D
       (n_185), .Q (\stateSub[1] ), .nQ (n_163));
  nand3 g16129(.A (n_261), .B (n_175), .C (n_256), .Y (n_262));
  nand2 g16136(.A (n_296), .B (n_286), .Y (n_260));
  nand2 g16141(.A (n_202), .B (n_163), .Y (n_259));
  nand2 g16149(.A (n_263), .B (n_147), .Y (n_283));
  and2 g16150(.A (n_257), .B (n_256), .Y (n_258));
  nand2 g16156(.A (n_333), .B (n_195), .Y (n_255));
  nand2 g16157(.A (n_296), .B (n_253), .Y (n_254));
  nand2 g16158(.A (n_257), .B (n_251), .Y (n_252));
  nand2 g16161(.A (n_263), .B (n_274), .Y (n_280));
  inv g16162(.A (n_249), .Y (n_250));
  nand2 g16169(.A (n_296), .B (\stateSub[0] ), .Y (n_248));
  nand2 g16170(.A (n_215), .B (n_173), .Y (n_247));
  nand3 g16175(.A (n_220), .B (n_245), .C (n_210), .Y (n_246));
  nand3 g16176(.A (n_19), .B (n_243), .C (OpcodeCondIn[3]), .Y (n_244));
  nand3 g16177(.A (n_93), .B (n_243), .C (OpcodeCondIn[6]), .Y (n_242));
  nand2 g16185(.A (n_162), .B (n_170), .Y (n_241));
  nand2 g16189(.A (n_239), .B (n_238), .Y (n_240));
  inv g16190(.A (n_208), .Y (n_237));
  inv g16225(.A (n_188), .Y (n_376));
  inv g16203(.A (n_204), .Y (n_236));
  nand2 g16213(.A (n_292), .B (n_238), .Y (n_235));
  and2 g16214(.A (n_140), .B (n_174), .Y (n_234));
  inv g16222(.A (n_232), .Y (WdSel));
  nand3 g16133(.A (n_181), .B (n_261), .C (n_230), .Y (n_231));
  nand3 g16220(.A (n_305), .B (n_228), .C (n_227), .Y (n_229));
  nand2 g16140(.A (n_178), .B (n_225), .Y (n_226));
  nand3 g16268(.A (n_142), .B (n_228), .C (n_30), .Y (n_224));
  nand2 g16144(.A (n_176), .B (n_144), .Y (n_223));
  nand2 g16146(.A (n_167), .B (n_102), .Y (n_222));
  nand3 g16152(.A (n_220), .B (n_199), .C (n_190), .Y (n_221));
  nand3 g16159(.A (n_213), .B (n_218), .C (n_50), .Y (n_219));
  nand2 g16163(.A (n_177), .B (n_114), .Y (n_249));
  nand3 g16167(.A (n_169), .B (n_92), .C (n_109), .Y (n_217));
  nand4 g16172(.A (n_56), .B (n_9), .C (n_143), .D (n_85), .Y (n_216));
  nand2 g16219(.A (n_158), .B (\state[1] ), .Y (n_215));
  nand4 g16178(.A (n_145), .B (n_47), .C (n_126), .D (n_107), .Y
       (n_214));
  nor2 g16180(.A (n_201), .B (OpcodeCondIn[6]), .Y (n_296));
  and2 g16181(.A (n_243), .B (n_213), .Y (n_257));
  nand2 g16182(.A (n_166), .B (\state[0] ), .Y (n_212));
  nand3 g16183(.A (n_210), .B (n_168), .C (OpcodeCondIn[7]), .Y
       (n_211));
  nand2 g16184(.A (n_243), .B (n_27), .Y (n_209));
  nor2 g16191(.A (n_218), .B (n_160), .Y (n_208));
  nand2 g16195(.A (n_243), .B (OpcodeCondIn[4]), .Y (n_207));
  nand2 g16197(.A (n_239), .B (n_228), .Y (n_206));
  and2 g16199(.A (n_243), .B (n_119), .Y (n_263));
  nand2 g16202(.A (n_197), .B (n_94), .Y (n_205));
  nor2 g16204(.A (n_203), .B (n_253), .Y (n_204));
  nand2 g16205(.A (n_201), .B (n_96), .Y (n_202));
  nand2 g16211(.A (n_199), .B (n_220), .Y (n_200));
  nand2 g16215(.A (n_197), .B (n_103), .Y (n_198));
  nand2 g16216(.A (n_197), .B (OpcodeCondIn[3]), .Y (n_196));
  nand2 g16218(.A (n_194), .B (n_193), .Y (n_195));
  nand3 g16223(.A (n_192), .B (n_191), .C (n_190), .Y (n_232));
  nand3 g16224(.A (n_192), .B (n_191), .C (n_210), .Y (n_189));
  nand4 g16226(.A (n_86), .B (n_180), .C (n_191), .D (OpcodeCondIn[7]),
       .Y (n_188));
  nand3 g16227(.A (n_220), .B (n_149), .C (n_190), .Y (n_187));
  and2 g16246(.A (n_266), .B (n_228), .Y (n_272));
  and2 g16247(.A (n_228), .B (OpcodeCondIn[7]), .Y (n_290));
  nand3 g16138(.A (OpcodeCondIn[7]), .B (n_182), .C (OpcodeCondIn[3]),
       .Y (n_186));
  nand3 g16139(.A (n_89), .B (n_148), .C (n_69), .Y (n_185));
  nand2 g16262(.A (n_191), .B (n_228), .Y (n_184));
  nand3 g16151(.A (n_256), .B (n_182), .C (OpcodeCondIn[3]), .Y
       (n_183));
  nand2 g16196(.A (n_138), .B (n_180), .Y (n_181));
  nand3 g16198(.A (n_291), .B (n_164), .C (n_161), .Y (n_179));
  nand2 g16206(.A (n_261), .B (n_155), .Y (n_178));
  nand2 g16207(.A (n_141), .B (\stateSub[2] ), .Y (n_177));
  nand2 g16209(.A (n_135), .B (OpcodeCondIn[3]), .Y (n_176));
  nand2 g16210(.A (n_63), .B (n_146), .Y (n_175));
  nand2 g16237(.A (n_133), .B (OpcodeCondIn[5]), .Y (n_174));
  nand2 g16241(.A (n_172), .B (nWait), .Y (n_173));
  nand2 g16259(.A (n_150), .B (n_171), .Y (n_238));
  nand2 g16261(.A (n_266), .B (n_220), .Y (n_170));
  nand2 g16265(.A (IntReq), .B (n_401), .Y (n_169));
  nand2 g16267(.A (n_168), .B (n_210), .Y (n_276));
  nand2 g16217(.A (n_136), .B (OpcodeCondIn[4]), .Y (n_167));
  nand2 g16229(.A (n_90), .B (n_113), .Y (n_166));
  nor2 g16230(.A (n_122), .B (n_72), .Y (n_194));
  and2 g16231(.A (n_333), .B (n_139), .Y (n_197));
  and2 g16232(.A (n_164), .B (n_163), .Y (n_165));
  nand2 g16233(.A (n_164), .B (n_161), .Y (n_162));
  and2 g16235(.A (n_333), .B (n_159), .Y (n_160));
  nand2 g16239(.A (n_117), .B (n_39), .Y (n_158));
  nand2 g16242(.A (n_164), .B (OpcodeCondIn[3]), .Y (n_201));
  nand2 g16248(.A (n_333), .B (n_75), .Y (n_157));
  and2 g16249(.A (n_333), .B (OpcodeCondIn[5]), .Y (n_243));
  inv g16250(.A (n_155), .Y (n_156));
  nand2 g16252(.A (n_154), .B (n_128), .Y (n_245));
  nand2 g16254(.A (n_333), .B (n_251), .Y (n_153));
  nor2 g16255(.A (n_164), .B (n_134), .Y (n_203));
  nand2 g16256(.A (n_154), .B (n_65), .Y (n_152));
  and2 g16257(.A (n_317), .B (\stateSub[0] ), .Y (n_239));
  and2 g16264(.A (n_333), .B (n_274), .Y (n_218));
  nand2 g16266(.A (n_154), .B (n_110), .Y (n_199));
  inv g16292(.A (n_401), .Y (PcSel[2]));
  inv g16296(.A (n_150), .Y (n_228));
  inv g16294(.A (n_118), .Y (n_149));
  nand2 g16228(.A (n_91), .B (\stateSub[1] ), .Y (n_148));
  nor2 g16234(.A (n_147), .B (OpcodeCondIn[4]), .Y (n_182));
  nand2 g16238(.A (\state[0] ), .B (n_105), .Y (n_146));
  nand2 g16240(.A (n_144), .B (n_137), .Y (n_145));
  nor2 g16243(.A (n_81), .B (n_142), .Y (n_143));
  nand2 g16244(.A (n_261), .B (n_104), .Y (n_141));
  nand2 g16245(.A (n_87), .B (n_180), .Y (n_140));
  nand3 g16251(.A (n_11), .B (n_121), .C (n_139), .Y (n_155));
  nand2 g16253(.A (n_137), .B (OpcodeCondIn[3]), .Y (n_138));
  nand2 g16258(.A (n_80), .B (n_7), .Y (n_136));
  nand2 g16260(.A (\stateSub[0] ), .B (n_137), .Y (n_135));
  nand2 g16282(.A (n_134), .B (n_163), .Y (n_308));
  and2 g16283(.A (n_180), .B (n_159), .Y (n_220));
  inv g16285(.A (n_120), .Y (n_133));
  inv g16287(.A (n_154), .Y (n_191));
  nand2 g16293(.A (n_100), .B (\state[1] ), .Y (n_401));
  nand2 g16297(.A (n_180), .B (OpcodeCondIn[3]), .Y (n_150));
  and2 g16298(.A (n_70), .B (n_180), .Y (n_168));
  nand2 g16301(.A (n_134), .B (n_88), .Y (n_132));
  nand2 g16302(.A (n_134), .B (n_261), .Y (n_404));
  nand2 g16304(.A (n_134), .B (n_130), .Y (n_131));
  nand2 g16305(.A (n_134), .B (n_17), .Y (n_129));
  inv g16307(.A (n_128), .Y (n_172));
  nand2 g16324(.A (n_134), .B (n_253), .Y (n_127));
  and2 g16208(.A (n_55), .B (n_171), .Y (n_230));
  nand2 g16236(.A (n_53), .B (n_125), .Y (n_126));
  and2 g16263(.A (n_59), .B (n_61), .Y (n_124));
  inv g16275(.A (n_137), .Y (n_123));
  nor2 g16278(.A (n_121), .B (OpcodeCondIn[5]), .Y (n_122));
  nor2 g16280(.A (n_171), .B (OpcodeCondIn[6]), .Y (n_192));
  and2 g16284(.A (n_266), .B (n_163), .Y (n_317));
  nor2 g16286(.A (n_71), .B (n_119), .Y (n_120));
  nand2 g16288(.A (n_301), .B (\stateSub[2] ), .Y (n_154));
  nor2 g16295(.A (n_301), .B (n_266), .Y (n_118));
  nor2 g16299(.A (n_68), .B (n_171), .Y (n_164));
  nand2 g16303(.A (n_62), .B (\stateSub[2] ), .Y (n_117));
  nand2 g16306(.A (n_78), .B (n_253), .Y (n_116));
  nand2 g16308(.A (n_266), .B (n_253), .Y (n_128));
  nand2 g16310(.A (n_266), .B (n_291), .Y (n_115));
  and2 g16314(.A (n_66), .B (n_114), .Y (n_311));
  nand2 g16316(.A (\stateSub[0] ), .B (n_106), .Y (n_113));
  nand2 g16318(.A (n_76), .B (\stateSub[1] ), .Y (n_112));
  nand2 g16319(.A (n_99), .B (\state[1] ), .Y (n_111));
  nand2 g16320(.A (n_266), .B (\stateSub[1] ), .Y (n_110));
  and2 g16321(.A (n_266), .B (n_261), .Y (n_333));
  nand2 g16322(.A (IRQ1), .B (n_484), .Y (n_109));
  nand2 g16325(.A (\stateSub[2] ), .B (n_95), .Y (n_108));
  nand2 g16327(.A (\state[0] ), .B (n_106), .Y (n_107));
  nor2 g16331(.A (n_274), .B (n_45), .Y (n_105));
  mux2 g16332(.S (OpcodeCondIn[6]), .I0 (n_305), .I1 (n_24), .Y
       (n_104));
  inv g16352(.A (n_102), .Y (n_103));
  nand2 g16300(.A (n_97), .B (n_130), .Y (n_101));
  inv g16362(.A (n_99), .Y (n_100));
  and2 g16309(.A (n_97), .B (n_253), .Y (IrWe));
  inv g16381(.A (n_96), .Y (n_134));
  inv g16378(.A (n_95), .Y (n_180));
  nand3 g16269(.A (n_42), .B (n_193), .C (n_93), .Y (n_94));
  nand2 g16271(.A (n_488), .B (IRQ2), .Y (n_92));
  nand2 g16272(.A (n_40), .B (n_77), .Y (n_91));
  nand2 g16273(.A (n_32), .B (n_161), .Y (n_90));
  nor2 g16276(.A (n_274), .B (n_227), .Y (n_137));
  nand2 g16277(.A (n_43), .B (n_88), .Y (n_89));
  nand2 g16279(.A (n_31), .B (n_305), .Y (n_147));
  nand2 g16289(.A (\stateSub[2] ), .B (n_86), .Y (n_87));
  nand3 g16291(.A (n_33), .B (n_34), .C (n_79), .Y (n_85));
  nand2 g16311(.A (n_97), .B (n_291), .Y (n_84));
  nand2 g16313(.A (n_97), .B (n_261), .Y (n_83));
  nand2 g16315(.A (n_36), .B (n_37), .Y (n_82));
  and2 g16326(.A (n_35), .B (n_227), .Y (n_81));
  nand3 g16323(.A (n_305), .B (n_79), .C (OpcodeCondIn[6]), .Y (n_80));
  inv g16333(.A (n_77), .Y (n_78));
  nand2 g16377(.A (\state[0] ), .B (n_75), .Y (n_76));
  nand2 g16340(.A (n_67), .B (n_14), .Y (n_73));
  nor2 g16341(.A (n_75), .B (OpcodeCondIn[7]), .Y (n_72));
  and2 g16343(.A (n_251), .B (n_213), .Y (n_71));
  inv g16344(.A (n_97), .Y (n_364));
  nor2 g16347(.A (n_70), .B (OpcodeCondIn[2]), .Y (n_142));
  nand2 g16349(.A (n_159), .B (n_75), .Y (n_171));
  nand2 g16351(.A (n_291), .B (n_225), .Y (n_69));
  nand2 g16353(.A (n_57), .B (n_159), .Y (n_102));
  inv g16354(.A (n_68), .Y (n_266));
  nand2 g16363(.A (n_261), .B (n_67), .Y (n_99));
  nand2 g16366(.A (n_253), .B (n_22), .Y (n_66));
  nand2 g16368(.A (\state[0] ), .B (n_251), .Y (n_345));
  nand2 g16370(.A (n_75), .B (OpcodeCondIn[3]), .Y (n_106));
  nand2 g16372(.A (n_292), .B (\stateSub[1] ), .Y (n_65));
  and2 g16375(.A (n_261), .B (n_64), .Y (n_301));
  nand2 g16382(.A (n_60), .B (\state[1] ), .Y (n_96));
  nand3 g16317(.A (n_13), .B (n_125), .C (OpcodeCondIn[2]), .Y (n_63));
  nand2 g16359(.A (n_261), .B (n_38), .Y (n_62));
  nand2 g16379(.A (n_75), .B (OpcodeCondIn[6]), .Y (n_95));
  nand2 g16376(.A (n_261), .B (n_60), .Y (n_61));
  nand3 g16290(.A (\stateSub[0] ), .B (n_58), .C (\state[1] ), .Y
       (n_59));
  nor2 g16374(.A (n_251), .B (n_57), .Y (n_121));
  nand3 g16328(.A (n_70), .B (n_485), .C (OpcodeCondIn[2]), .Y (n_56));
  nand4 g16270(.A (OpcodeCondIn[3]), .B (n_256), .C (n_139), .D
       (OpcodeCondIn[4]), .Y (n_55));
  and2 g16371(.A (n_57), .B (n_256), .Y (n_119));
  nand3 g16274(.A (n_251), .B (\state[0] ), .C (n_139), .Y (n_54));
  nand2 g16281(.A (n_18), .B (n_23), .Y (n_53));
  nand2 g16369(.A (n_60), .B (nWait), .Y (n_52));
  nand3 g16312(.A (n_159), .B (\stateSub[1] ), .C (n_50), .Y (n_51));
  nand3 g16329(.A (OpcodeCondIn[6]), .B (n_93), .C (OpcodeCondIn[5]),
       .Y (n_49));
  nand3 g16330(.A (n_25), .B (\state[0] ), .C (OpcodeCondIn[5]), .Y
       (n_48));
  nand2 g16364(.A (n_130), .B (n_10), .Y (n_47));
  nand2 g16334(.A (n_125), .B (n_0), .Y (n_77));
  scandtype IRQ2_reg(.nReset (nReset), .Clock (Clock), .D (IRQ1), .Q
       (IRQ2), .nQ (n_484));
  nand2 g16337(.A (n_347), .B (n_163), .Y (n_46));
  nor2 g16339(.A (n_44), .B (OpcodeCondIn[0]), .Y (n_45));
  nand2 g16342(.A (n_21), .B (n_58), .Y (n_43));
  nand2 g16346(.A (n_159), .B (n_50), .Y (n_42));
  nand2 g16348(.A (\state[0] ), .B (n_28), .Y (n_41));
  nand2 g16357(.A (n_58), .B (\state[1] ), .Y (n_40));
  nand2 g16358(.A (n_253), .B (n_38), .Y (n_39));
  and2 g16360(.A (n_44), .B (OpcodeCondIn[0]), .Y (n_274));
  nand2 g16361(.A (n_144), .B (OpcodeCondIn[4]), .Y (n_37));
  and2 g16365(.A (n_210), .B (n_227), .Y (n_86));
  nand2 g16367(.A (n_253), .B (OpcodeCondIn[6]), .Y (n_36));
  nand2 g16373(.A (n_20), .B (n_26), .Y (n_269));
  nand2 g16385(.A (n_34), .B (n_33), .Y (n_35));
  nand2 g16338(.A (n_6), .B (n_8), .Y (n_32));
  nand2 g16380(.A (n_16), .B (n_30), .Y (n_31));
  nand2 g16355(.A (n_64), .B (n_225), .Y (n_68));
  nand2 g16350(.A (\stateSub[2] ), .B (n_28), .Y (n_29));
  nor2 g16345(.A (n_58), .B (\state[1] ), .Y (n_97));
  xor2 g16384(.A (n_159), .B (OpcodeCondIn[3]), .Y (n_27));
  inv g16390(.A (n_28), .Y (n_75));
  inv g16397(.A (n_30), .Y (n_79));
  inv g16401(.A (n_130), .Y (n_261));
  inv g16410(.A (n_26), .Y (n_88));
  inv g16421(.A (n_25), .Y (n_251));
  inv g16405(.A (n_23), .Y (n_24));
  inv g16417(.A (n_346), .Y (n_67));
  inv g16399(.A (n_347), .Y (n_22));
  inv g16392(.A (n_21), .Y (n_292));
  inv g16412(.A (n_20), .Y (n_291));
  inv g16414(.A (n_93), .Y (n_57));
  inv g16403(.A (n_58), .Y (n_60));
  inv g16408(.A (n_193), .Y (n_19));
  nand2 g16356(.A (n_17), .B (n_12), .Y (n_18));
  inv g16395(.A (n_16), .Y (n_70));
  nand2 g16402(.A (n_286), .B (n_163), .Y (n_130));
  nand2 g16396(.A (n_15), .B (OpcodeCondIn[1]), .Y (n_16));
  nand2 g16415(.A (n_161), .B (OpcodeCondIn[4]), .Y (n_93));
  nand2 g16388(.A (\StatusReg[2] ), .B (n_486), .Y (n_34));
  nand2 g16389(.A (\StatusReg[3] ), .B (n_487), .Y (n_33));
  nand2 g16393(.A (n_225), .B (n_14), .Y (n_21));
  nand2 g16406(.A (n_13), .B (OpcodeCondIn[7]), .Y (n_23));
  and2 g16407(.A (n_305), .B (OpcodeCondIn[1]), .Y (n_44));
  nor2 g16424(.A (n_38), .B (n_159), .Y (n_144));
  nand2 g16409(.A (n_12), .B (OpcodeCondIn[4]), .Y (n_193));
  inv g16432(.A (n_190), .Y (n_210));
  nand2 g16420(.A (n_159), .B (OpcodeCondIn[4]), .Y (n_11));
  nand2 g16419(.A (\state[0] ), .B (n_12), .Y (n_10));
  inv g16430(.A (n_17), .Y (n_253));
  nand3 g16383(.A (OpcodeCondIn[0]), .B (\StatusReg[0] ), .C
       (OpcodeCondIn[1]), .Y (n_9));
  nand2 g16391(.A (n_139), .B (n_213), .Y (n_28));
  nand2 g16418(.A (\stateSub[2] ), .B (n_38), .Y (n_346));
  nor2 g16416(.A (\state[1] ), .B (n_38), .Y (n_64));
  nand2 g16404(.A (n_225), .B (n_38), .Y (n_58));
  nand2 g16411(.A (\stateSub[0] ), .B (n_163), .Y (n_26));
  scandtype IRQ1_reg(.nReset (nReset), .Clock (Clock), .D (n_3), .Q
       (IRQ1), .nQ ());
  inv g16425(.A (n_8), .Y (n_256));
  nand2 g16422(.A (n_12), .B (OpcodeCondIn[7]), .Y (n_25));
  nand2 g16398(.A (n_13), .B (OpcodeCondIn[0]), .Y (n_30));
  nand2 g16413(.A (\stateSub[1] ), .B (n_286), .Y (n_20));
  inv g16428(.A (n_7), .Y (n_50));
  and2 g16423(.A (n_225), .B (\state[0] ), .Y (n_125));
  nand2 g16400(.A (n_38), .B (n_14), .Y (n_347));
  nand2 g16394(.A (n_163), .B (n_139), .Y (n_6));
  nand2 g16433(.A (OpcodeCondIn[2]), .B (OpcodeCondIn[3]), .Y (n_190));
  nor2 g16387(.A (OpcodeCondIn[1]), .B (OpcodeCondIn[0]), .Y (n_227));
  nand2 g16431(.A (\stateSub[1] ), .B (\stateSub[0] ), .Y (n_17));
  nand2 g16427(.A (\state[0] ), .B (\state[1] ), .Y (n_114));
  nand2 g16429(.A (OpcodeCondIn[6]), .B (OpcodeCondIn[3]), .Y (n_7));
  nand2 g16426(.A (OpcodeCondIn[6]), .B (OpcodeCondIn[7]), .Y (n_8));
  inv g16436(.A (OpcodeCondIn[3]), .Y (n_161));
  inv g16434(.A (OpcodeCondIn[7]), .Y (n_159));
  inv g16443(.A (OpcodeCondIn[1]), .Y (n_13));
  inv g16451(.A (OpcodeCondIn[4]), .Y (n_213));
  inv g16437(.A (nIRQ), .Y (n_3));
  inv g16452(.A (OpcodeCondIn[0]), .Y (n_15));
  inv g16447(.A (OpcodeCondIn[6]), .Y (n_12));
  inv g16440(.A (OpcodeCondIn[5]), .Y (n_139));
  inv g16435(.A (nWait), .Y (n_0));
  inv g16445(.A (OpcodeCondIn[2]), .Y (n_305));
endmodule

